/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
typedef unsigned int size_t;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@ behavior default:
      assigns \at(\result,Post) \from __size;  */
extern  __attribute__((__nothrow__)) struct char_P *malloc(size_t __size )  __attribute__((
__malloc__)) ;
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
intlist init(int len ) ;
/*Loc=../../../c/intlist-lib-init.c(7,7)*//*@ requires //id:67
                                                       (len ≥ 1);
                                              behavior default:
                                                
                                            
                                          */
                                          intlist init(int len ) 
{
  intlist curr ;
  intlist head ;
  int i ;
  /*Loc=../../../c/intlist-lib-init.c:(11,11)*//*sid:1*/
  head = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-lib-init.c:(12,12)*//*sid:2*/
  curr = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-lib-init.c:(14,14)*//*sid:3*/
  i = 1;
  /*Loc=../../../c/intlist-lib-init.c:(14,14)*//*sid:4*/
  while (i <= len) {
    /*Loc=../../../c/intlist-lib-init.c:(15,15)*//*sid:8*/
    curr = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-lib-init.c:(16,16)*//*sid:9*/
    curr->data = 0;
    /*Loc=../../../c/intlist-lib-init.c:(17,17)*//*sid:10*/
    curr->next = head;
    /*Loc=../../../c/intlist-lib-init.c:(18,18)*//*sid:11*/
    head = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-lib-init.c:(19,19)*//*sid:12*/
    head = curr;
    /*Loc=../../../c/intlist-lib-init.c:(20,20)*//*sid:13*/
    curr = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-lib-init.c:(14,14)*//*sid:14*/
    i ++;
  }
  /*Loc=../../../c/intlist-lib-init.c:(22,22)*//*sid:15*/
  return (head);
}


