/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
typedef unsigned int size_t;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@ behavior default:
      assigns \at(\result,Post) \from __size;  */
extern  __attribute__((__nothrow__)) struct char_P *malloc(size_t __size )  __attribute__((
__malloc__)) ;
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
intlist fold2_concat(intlist x , intlist y ) ;
/*Loc=../../../c/intlist-fold2-concat.c(8,8)*//*@ requires //id:67
                                                           ((acyclic{Here}(x)
                                                            ∧
                                                            acyclic{Here}(y))
                                                           ∧
                                                           disjoint{Here}
                                                           (x, y));
                                                  behavior default:
                                                    
                                                
                                              */
                                              intlist fold2_concat(intlist x ,
                                                                   intlist y ) 
{
  intlist r ;
  intlist z ;
  intlist zi ;
  intlist tmp ;
  intlist li ;
  /*Loc=../../../c/intlist-fold2-concat.c:(10,10)*//*sid:1*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-fold2-concat.c:(10,10)*//*sid:2*/
    li = (struct intlist_ *)((struct char_P *)0);
    /*effects: li <- */
    /*Loc=../../../c/intlist-fold2-concat.c:(10,10)*//*sid:3*/
    tmp = li;
    /*effects: tmp <- */
    /*Loc=../../../c/intlist-fold2-concat.c:(10,10)*//*sid:4*/
    zi = tmp;
    /*effects: zi <- */
    /*Loc=../../../c/intlist-fold2-concat.c:(10,10)*//*sid:5*/
    z = zi;
    /*effects: z <- */
    /*Loc=../../../c/intlist-fold2-concat.c:(10,10)*//*sid:6*/
    r = z;
    /*effects: r <- */
  }
  /*Loc=../../../c/intlist-fold2-concat.c:(12,12)*//*sid:7*/
  li = x;
  /*Loc=../../../c/intlist-fold2-concat.c:(13,13)*//*sid:8*/
  while (li != (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold2-concat.c:(14,14)*//*sid:12*/
    zi = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-fold2-concat.c:(15,15)*//*sid:13*/
    zi->data = li->data;
    /*Loc=../../../c/intlist-fold2-concat.c:(16,16)*//*sid:14*/
    zi->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-concat.c:(17,17)*//*sid:16*/
    if (r == (struct char_P *)0) {
      /*Loc=../../../c/intlist-fold2-concat.c:(18,18)*//*sid:17*/
      r = zi;
      /*Loc=../../../c/intlist-fold2-concat.c:(19,19)*//*sid:18*/
      z = zi;
    }
    else {
      /*Loc=../../../c/intlist-fold2-concat.c:(21,21)*//*sid:19*/
      z->next = zi;
      /*Loc=../../../c/intlist-fold2-concat.c:(22,22)*//*sid:20*/
      z = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold2-concat.c:(23,23)*//*sid:21*/
      z = zi;
    }
    /*Loc=../../../c/intlist-fold2-concat.c:(25,25)*//*sid:22*/
    zi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-concat.c:(26,26)*//*sid:23*/
    zi = li->next;
    /*Loc=../../../c/intlist-fold2-concat.c:(27,27)*//*sid:24*/
    li = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-concat.c:(28,28)*//*sid:25*/
    li = zi;
    /*Loc=../../../c/intlist-fold2-concat.c:(29,29)*//*sid:26*/
    zi = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-fold2-concat.c:(32,32)*//*sid:27*/
  li = y;
  /*Loc=../../../c/intlist-fold2-concat.c:(33,33)*//*sid:28*/
  while (li != (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold2-concat.c:(34,34)*//*sid:32*/
    zi = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-fold2-concat.c:(35,35)*//*sid:33*/
    zi->data = li->data;
    /*Loc=../../../c/intlist-fold2-concat.c:(36,36)*//*sid:34*/
    zi->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-concat.c:(37,37)*//*sid:36*/
    if (r == (struct char_P *)0) {
      /*Loc=../../../c/intlist-fold2-concat.c:(38,38)*//*sid:37*/
      r = zi;
      /*Loc=../../../c/intlist-fold2-concat.c:(39,39)*//*sid:38*/
      z = zi;
    }
    else {
      /*Loc=../../../c/intlist-fold2-concat.c:(41,41)*//*sid:39*/
      z->next = zi;
      /*Loc=../../../c/intlist-fold2-concat.c:(42,42)*//*sid:40*/
      z = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold2-concat.c:(43,43)*//*sid:41*/
      z = zi;
    }
    /*Loc=../../../c/intlist-fold2-concat.c:(45,45)*//*sid:42*/
    zi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-concat.c:(46,46)*//*sid:43*/
    zi = li->next;
    /*Loc=../../../c/intlist-fold2-concat.c:(47,47)*//*sid:44*/
    li = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-concat.c:(48,48)*//*sid:45*/
    li = zi;
    /*Loc=../../../c/intlist-fold2-concat.c:(49,49)*//*sid:46*/
    zi = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-fold2-concat.c:(51,51)*//*sid:47*/
  z = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-fold2-concat.c:(52,52)*//*sid:48*/
  return (r);
}


