
all:
	$(VALGRIND) ../../../../frama-c-plugin/frama-c-Celia.byte -celia -celia-cinv-opt ucons.prop  ../../../c/intlist-lib-init.c ../../../c/intlist-lib-add.c ../../../c/intlist-map-initV.c ../../../c/intlist-main-htable-add.c

clean:
	rm *.shp pan* *.txt sid_*
