/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
typedef unsigned int size_t;
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
intlist init(int len ) ;
intlist add(intlist head , int value ) ;
/*@ requires //id:213
             acyclic{Here}(head_1);
    behavior default:
      assigns head_1->data, head_1->next;
      assigns head_1->data \from head_1->data, head_1->next, v_0;
      assigns head_1->next \from head_1->data, head_1->next, v_0;
  
*/
extern void map_initSeq(intlist head_1 , int v_0 ) ;
void initV(intlist head_0 , int v ) ;
/*Loc=../../../c/intlist-main-htable-add.c(6,6)*//*@ behavior default:
                                                         */
                                                 void main(void) 
{
  intlist h_0 ;
  intlist h_1 ;
  intlist h_2 ;
  intlist h_3 ;
  intlist h_other ;
  intlist x ;
  intlist tmp ;
  intlist xi ;
  int d ;
  /*Loc=../../../c/intlist-main-htable-add.c:(15,15)*//*sid:1*/
  d = 3;
  /*Loc=../../../c/intlist-main-htable-add.c:(15,15)*//*sid:2*/
  h_0 = init(d);
  /*Loc=../../../c/intlist-main-htable-add.c:(16,16)*//*sid:3*/
  d = 2;
  /*Loc=../../../c/intlist-main-htable-add.c:(16,16)*//*sid:4*/
  h_1 = init(d);
  /*Loc=../../../c/intlist-main-htable-add.c:(17,17)*//*sid:5*/
  d = 1;
  /*Loc=../../../c/intlist-main-htable-add.c:(17,17)*//*sid:6*/
  h_2 = init(d);
  /*Loc=../../../c/intlist-main-htable-add.c:(18,18)*//*sid:7*/
  d = 2;
  /*Loc=../../../c/intlist-main-htable-add.c:(18,18)*//*sid:8*/
  h_3 = init(d);
  /*Loc=../../../c/intlist-main-htable-add.c:(19,19)*//*sid:9*/
  h_other = init(d);
  /*Loc=../../../c/intlist-main-htable-add.c:(20,20)*//*sid:10*/
  d = 4;
  /*Loc=../../../c/intlist-main-htable-add.c:(20,20)*//*sid:11*/
  x = init(d);
  /*Loc=../../../c/intlist-main-htable-add.c:(22,22)*//*sid:12*/
  d = 0;
  /*Loc=../../../c/intlist-main-htable-add.c:(22,22)*//*sid:13*/
  initV(h_0,d);
  /*Loc=../../../c/intlist-main-htable-add.c:(23,23)*//*sid:14*/
  d = 1;
  /*Loc=../../../c/intlist-main-htable-add.c:(23,23)*//*sid:15*/
  initV(h_1,d);
  /*Loc=../../../c/intlist-main-htable-add.c:(24,24)*//*sid:16*/
  d = 2;
  /*Loc=../../../c/intlist-main-htable-add.c:(24,24)*//*sid:17*/
  initV(h_2,d);
  /*Loc=../../../c/intlist-main-htable-add.c:(25,25)*//*sid:18*/
  d = 3;
  /*Loc=../../../c/intlist-main-htable-add.c:(25,25)*//*sid:19*/
  initV(h_3,d);
  /*Loc=../../../c/intlist-main-htable-add.c:(26,26)*//*sid:20*/
  d = 4;
  /*Loc=../../../c/intlist-main-htable-add.c:(26,26)*//*sid:21*/
  map_initSeq(h_other,d);
  /*Loc=../../../c/intlist-main-htable-add.c:(27,27)*//*sid:22*/
  d = 0;
  /*Loc=../../../c/intlist-main-htable-add.c:(27,27)*//*sid:23*/
  map_initSeq(x,d);
  /*Loc=../../../c/intlist-main-htable-add.c:(29,29)*//*sid:24*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-main-htable-add.c:(29,29)*//*sid:25*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*effects: tmp <- */
    /*Loc=../../../c/intlist-main-htable-add.c:(29,29)*//*sid:26*/
    xi = tmp;
    /*effects: xi <- */
  }
  /*Loc=../../../c/intlist-main-htable-add.c:(30,30)*//*sid:27*/
  xi = x;
  /*Loc=../../../c/intlist-main-htable-add.c:(31,31)*//*sid:28*/
  while (xi) {
    /*Loc=../../../c/intlist-main-htable-add.c:(32,32)*//*sid:32*/
    d = xi->data;
    /*Loc=../../../c/intlist-main-htable-add.c:(33,33)*//*sid:34*/
    if (d == 0) {
      /*Loc=../../../c/intlist-main-htable-add.c:(34,34)*//*sid:35*/
      tmp = add(h_0,d);
      /*Loc=../../../c/intlist-main-htable-add.c:(35,35)*//*sid:36*/
      h_0 = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-main-htable-add.c:(36,36)*//*sid:37*/
      h_0 = tmp;
      /*Loc=../../../c/intlist-main-htable-add.c:(37,37)*//*sid:38*/
      tmp = (struct intlist_ *)((struct char_P *)0);
    }
    else {
      /*Loc=../../../c/intlist-main-htable-add.c:(39,39)*//*sid:40*/
      if (d == 1) {
        /*Loc=../../../c/intlist-main-htable-add.c:(40,40)*//*sid:41*/
        tmp = add(h_1,d);
        /*Loc=../../../c/intlist-main-htable-add.c:(41,41)*//*sid:42*/
        h_1 = (struct intlist_ *)((struct char_P *)0);
        /*Loc=../../../c/intlist-main-htable-add.c:(42,42)*//*sid:43*/
        h_1 = tmp;
        /*Loc=../../../c/intlist-main-htable-add.c:(43,43)*//*sid:44*/
        tmp = (struct intlist_ *)((struct char_P *)0);
      }
      else {
        /*Loc=../../../c/intlist-main-htable-add.c:(45,45)*//*sid:46*/
        if (d == 2) {
          /*Loc=../../../c/intlist-main-htable-add.c:(46,46)*//*sid:47*/
          tmp = add(h_2,d);
          /*Loc=../../../c/intlist-main-htable-add.c:(47,47)*//*sid:48*/
          h_2 = (struct intlist_ *)((struct char_P *)0);
          /*Loc=../../../c/intlist-main-htable-add.c:(48,48)*//*sid:49*/
          h_2 = tmp;
          /*Loc=../../../c/intlist-main-htable-add.c:(49,49)*//*sid:50*/
          tmp = (struct intlist_ *)((struct char_P *)0);
        }
        else {
          /*Loc=../../../c/intlist-main-htable-add.c:(51,51)*//*sid:52*/
          if (d == 3) {
            /*Loc=../../../c/intlist-main-htable-add.c:(52,52)*//*sid:53*/
            tmp = add(h_3,d);
            /*Loc=../../../c/intlist-main-htable-add.c:(53,53)*//*sid:54*/
            h_3 = (struct intlist_ *)((struct char_P *)0);
            /*Loc=../../../c/intlist-main-htable-add.c:(54,54)*//*sid:55*/
            h_3 = tmp;
            /*Loc=../../../c/intlist-main-htable-add.c:(55,55)*//*sid:56*/
            tmp = (struct intlist_ *)((struct char_P *)0);
          }
          else {
            /*Loc=../../../c/intlist-main-htable-add.c:(58,58)*//*sid:57*/
            tmp = add(h_other,d);
            /*Loc=../../../c/intlist-main-htable-add.c:(59,59)*//*sid:58*/
            h_other = (struct intlist_ *)((struct char_P *)0);
            /*Loc=../../../c/intlist-main-htable-add.c:(60,60)*//*sid:59*/
            h_other = tmp;
            /*Loc=../../../c/intlist-main-htable-add.c:(61,61)*//*sid:60*/
            tmp = (struct intlist_ *)((struct char_P *)0);
          }
        }
      }
    }
    /*Loc=../../../c/intlist-main-htable-add.c:(63,63)*//*sid:61*/
    tmp = xi->next;
    /*Loc=../../../c/intlist-main-htable-add.c:(64,64)*//*sid:62*/
    xi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-main-htable-add.c:(65,65)*//*sid:63*/
    xi = tmp;
    /*Loc=../../../c/intlist-main-htable-add.c:(66,66)*//*sid:64*/
    tmp = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-main-htable-add.c:(69,69)*//*sid:101*/
  return;
}

/*Loc=../../../c/intlist-map-initV.c(9,9)*//*@ requires //id:201
                                                        acyclic{Here}(head_0);
                                               behavior default:
                                                 
                                             
                                           */
                                           void initV(intlist head_0 , int v ) 
{
  intlist h ;
  intlist tmp_0 ;
  /*Loc=../../../c/intlist-map-initV.c:(11,11)*//*sid:66*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-map-initV.c:(11,11)*//*sid:67*/
    tmp_0 = (struct intlist_ *)((struct char_P *)0);
    /*effects: tmp_0 <- */
    /*Loc=../../../c/intlist-map-initV.c:(11,11)*//*sid:68*/
    h = tmp_0;
    /*effects: h <- */
  }
  /*Loc=../../../c/intlist-map-initV.c:(12,12)*//*sid:69*/
  h = head_0;
  /*Loc=../../../c/intlist-map-initV.c:(13,13)*//*sid:70*/
  while (h != (struct char_P *)0) {
    /*Loc=../../../c/intlist-map-initV.c:(14,14)*//*sid:74*/
    h->data = v;
    /*Loc=../../../c/intlist-map-initV.c:(15,15)*//*sid:75*/
    tmp_0 = h->next;
    /*Loc=../../../c/intlist-map-initV.c:(16,16)*//*sid:76*/
    h = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-map-initV.c:(17,17)*//*sid:77*/
    h = tmp_0;
    /*Loc=../../../c/intlist-map-initV.c:(18,18)*//*sid:78*/
    tmp_0 = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-map-initV.c:(20,20)*//*sid:102*/
  return;
}

/*@ behavior default:
      assigns \at(\result,Post) \from __size;  */
extern  __attribute__((__nothrow__)) struct char_P *malloc(size_t __size )  __attribute__((
__malloc__)) ;
/*Loc=../../../c/intlist-lib-add.c(9,9)*//*@ requires //id:134
                                                      acyclic{Here}(head);
                                             behavior default:
                                               
                                           
                                         */
                                         intlist add(intlist head ,
                                                     int value ) 
{
  intlist curr ;
  /*Loc=../../../c/intlist-lib-add.c:(11,11)*//*sid:80*/
  curr = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-lib-add.c:(12,12)*//*sid:81*/
  curr = (intlist )malloc(sizeof(struct intlist_ ));
  /*Loc=../../../c/intlist-lib-add.c:(13,13)*//*sid:82*/
  curr->data = value;
  /*Loc=../../../c/intlist-lib-add.c:(14,14)*//*sid:83*/
  curr->next = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-lib-add.c:(15,15)*//*sid:84*/
  curr->next = head;
  /*Loc=../../../c/intlist-lib-add.c:(16,16)*//*sid:85*/
  return (curr);
}

/*Loc=../../../c/intlist-lib-init.c(7,7)*//*@ requires //id:67
                                                       (len ≥ 1);
                                              behavior default:
                                                
                                            
                                          */
                                          intlist init(int len ) 
{
  intlist curr_0 ;
  intlist head_2 ;
  int i ;
  /*Loc=../../../c/intlist-lib-init.c:(11,11)*//*sid:86*/
  head_2 = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-lib-init.c:(12,12)*//*sid:87*/
  curr_0 = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-lib-init.c:(14,14)*//*sid:88*/
  i = 1;
  /*Loc=../../../c/intlist-lib-init.c:(14,14)*//*sid:89*/
  while (i <= len) {
    /*Loc=../../../c/intlist-lib-init.c:(15,15)*//*sid:93*/
    curr_0 = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-lib-init.c:(16,16)*//*sid:94*/
    curr_0->data = 0;
    /*Loc=../../../c/intlist-lib-init.c:(17,17)*//*sid:95*/
    curr_0->next = head_2;
    /*Loc=../../../c/intlist-lib-init.c:(18,18)*//*sid:96*/
    head_2 = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-lib-init.c:(19,19)*//*sid:97*/
    head_2 = curr_0;
    /*Loc=../../../c/intlist-lib-init.c:(20,20)*//*sid:98*/
    curr_0 = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-lib-init.c:(14,14)*//*sid:99*/
    i ++;
  }
  /*Loc=../../../c/intlist-lib-init.c:(22,22)*//*sid:100*/
  return (head_2);
}


