#! /bin/make

clean:
	rm -f cinv.log cinv.dvi cinv.ky cinv.tp cinv.toc cinv.vr cinv.aux cinv.cp cinv.fn cinv.pg 
	/bin/rm -f *.[ao] 
	/bin/rm -f *.?.tex *.log *.aux *.bbl *.blg *.toc *.dvi *.ps *.pstex*
	/bin/rm -fr *.annot *.cm[ioax] *.cmxa clim
	/bin/rm -fr *~ \#*\# *.BAK f_*.shp

dist-clean: clean
	/bin/rm -fr *_caml.c *.mli
	rm -f cinv.pdf cinv_version.ml


