/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
typedef unsigned int size_t;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@ behavior default:
      assigns \at(\result,Post) \from __size;  */
extern  __attribute__((__nothrow__)) struct char_P *malloc(size_t __size )  __attribute__((
__malloc__)) ;
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
intlist fold2_merge(intlist x , intlist y ) ;
/*Loc=../../../c/intlist-fold2-merge.c(10,10)*//*@ requires //id:67
                                                            ((acyclic{
                                                              Here}(x)
                                                             ∧
                                                             acyclic{Here}(y))
                                                            ∧
                                                            disjoint{
                                                            Here}(x, y));
                                                   behavior default:
                                                     
                                                 
                                               */
                                               intlist fold2_merge(intlist x ,
                                                                   intlist y ) 
{
  intlist r ;
  intlist ri ;
  intlist xi ;
  intlist yi ;
  intlist tmp ;
  int v ;
  /*Loc=../../../c/intlist-fold2-merge.c:(13,13)*//*sid:1*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-fold2-merge.c:(13,13)*//*sid:2*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*effects: tmp <- */
    /*Loc=../../../c/intlist-fold2-merge.c:(13,13)*//*sid:3*/
    yi = tmp;
    /*effects: yi <- */
    /*Loc=../../../c/intlist-fold2-merge.c:(13,13)*//*sid:4*/
    xi = yi;
    /*effects: xi <- */
    /*Loc=../../../c/intlist-fold2-merge.c:(13,13)*//*sid:5*/
    ri = xi;
    /*effects: ri <- */
    /*Loc=../../../c/intlist-fold2-merge.c:(13,13)*//*sid:6*/
    r = ri;
    /*effects: r <- */
  }
  /*Loc=../../../c/intlist-fold2-merge.c:(14,14)*//*sid:7*/
  xi = x;
  /*Loc=../../../c/intlist-fold2-merge.c:(15,15)*//*sid:8*/
  yi = y;
  /*Loc=../../../c/intlist-fold2-merge.c:(16,16)*//*sid:9*/
  while (1) {
    /*Loc=../../../c/intlist-fold2-merge.c:(16,16)*//*sid:11*/
    if (xi != (struct char_P *)0) {
      /*Loc=../../../c/intlist-fold2-merge.c:(16,16)*//*sid:13*/
      if (! (yi != (struct char_P *)0)) {
        /*Loc=../../../c/intlist-fold2-merge.c:(16,16)*//*sid:14*/
        break;
      }
    }
    else { /*Loc=../../../c/intlist-fold2-merge.c:(16,16)*//*sid:15*/ break;
    }
    /*Loc=../../../c/intlist-fold2-merge.c:(17,17)*//*sid:17*/
    if (xi->data < yi->data) {
      /*Loc=../../../c/intlist-fold2-merge.c:(18,18)*//*sid:18*/
      v = xi->data;
      /*Loc=../../../c/intlist-fold2-merge.c:(19,19)*//*sid:19*/
      tmp = xi->next;
      /*Loc=../../../c/intlist-fold2-merge.c:(20,20)*//*sid:20*/
      xi = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold2-merge.c:(21,21)*//*sid:21*/
      xi = tmp;
      /*Loc=../../../c/intlist-fold2-merge.c:(22,22)*//*sid:22*/
      tmp = (struct intlist_ *)((struct char_P *)0);
    }
    else {
      /*Loc=../../../c/intlist-fold2-merge.c:(24,24)*//*sid:23*/
      v = yi->data;
      /*Loc=../../../c/intlist-fold2-merge.c:(25,25)*//*sid:24*/
      tmp = yi->next;
      /*Loc=../../../c/intlist-fold2-merge.c:(26,26)*//*sid:25*/
      yi = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold2-merge.c:(27,27)*//*sid:26*/
      yi = tmp;
      /*Loc=../../../c/intlist-fold2-merge.c:(28,28)*//*sid:27*/
      tmp = (struct intlist_ *)((struct char_P *)0);
    }
    /*Loc=../../../c/intlist-fold2-merge.c:(31,31)*//*sid:28*/
    tmp = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-fold2-merge.c:(32,32)*//*sid:29*/
    tmp->data = v;
    /*Loc=../../../c/intlist-fold2-merge.c:(33,33)*//*sid:30*/
    tmp->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(34,34)*//*sid:32*/
    if (r == (struct char_P *)0) {
      /*Loc=../../../c/intlist-fold2-merge.c:(35,35)*//*sid:33*/
      r = tmp;
      /*Loc=../../../c/intlist-fold2-merge.c:(36,36)*//*sid:34*/
      ri = tmp;
    }
    else {
      /*Loc=../../../c/intlist-fold2-merge.c:(38,38)*//*sid:35*/
      ri->next = tmp;
      /*Loc=../../../c/intlist-fold2-merge.c:(39,39)*//*sid:36*/
      ri = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold2-merge.c:(40,40)*//*sid:37*/
      ri = tmp;
    }
    /*Loc=../../../c/intlist-fold2-merge.c:(42,42)*//*sid:38*/
    tmp = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-fold2-merge.c:(44,44)*//*sid:39*/
  while (xi != (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold2-merge.c:(46,46)*//*sid:43*/
    tmp = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-fold2-merge.c:(47,47)*//*sid:44*/
    tmp->data = xi->data;
    /*Loc=../../../c/intlist-fold2-merge.c:(48,48)*//*sid:45*/
    tmp->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(49,49)*//*sid:47*/
    if (r == (struct char_P *)0) {
      /*Loc=../../../c/intlist-fold2-merge.c:(50,50)*//*sid:48*/
      r = tmp;
      /*Loc=../../../c/intlist-fold2-merge.c:(51,51)*//*sid:49*/
      ri = tmp;
    }
    else {
      /*Loc=../../../c/intlist-fold2-merge.c:(53,53)*//*sid:50*/
      ri->next = tmp;
      /*Loc=../../../c/intlist-fold2-merge.c:(54,54)*//*sid:51*/
      ri = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold2-merge.c:(55,55)*//*sid:52*/
      ri = tmp;
    }
    /*Loc=../../../c/intlist-fold2-merge.c:(57,57)*//*sid:53*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(58,58)*//*sid:54*/
    tmp = xi->next;
    /*Loc=../../../c/intlist-fold2-merge.c:(59,59)*//*sid:55*/
    xi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(60,60)*//*sid:56*/
    xi = tmp;
    /*Loc=../../../c/intlist-fold2-merge.c:(61,61)*//*sid:57*/
    tmp = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-fold2-merge.c:(63,63)*//*sid:58*/
  while (yi != (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold2-merge.c:(64,64)*//*sid:62*/
    tmp = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-fold2-merge.c:(65,65)*//*sid:63*/
    tmp->data = yi->data;
    /*Loc=../../../c/intlist-fold2-merge.c:(66,66)*//*sid:64*/
    tmp->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(67,67)*//*sid:66*/
    if (r == (struct char_P *)0) {
      /*Loc=../../../c/intlist-fold2-merge.c:(68,68)*//*sid:67*/
      r = tmp;
      /*Loc=../../../c/intlist-fold2-merge.c:(69,69)*//*sid:68*/
      ri = tmp;
    }
    else {
      /*Loc=../../../c/intlist-fold2-merge.c:(71,71)*//*sid:69*/
      ri->next = tmp;
      /*Loc=../../../c/intlist-fold2-merge.c:(72,72)*//*sid:70*/
      ri = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold2-merge.c:(73,73)*//*sid:71*/
      ri = tmp;
    }
    /*Loc=../../../c/intlist-fold2-merge.c:(75,75)*//*sid:72*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(76,76)*//*sid:73*/
    tmp = yi->next;
    /*Loc=../../../c/intlist-fold2-merge.c:(77,77)*//*sid:74*/
    yi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(78,78)*//*sid:75*/
    yi = tmp;
    /*Loc=../../../c/intlist-fold2-merge.c:(79,79)*//*sid:76*/
    tmp = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-fold2-merge.c:(81,81)*//*sid:77*/
  ri = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-fold2-merge.c:(82,82)*//*sid:78*/
  return (r);
}


