/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
/*@ behavior default:
      assigns \nothing;  */
struct char_P *malloc(unsigned int size ) ;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
/*Loc=../../../c/intlist-sort-insert.c(9,9)*//*@ requires //id:67
                                                          acyclic{Here}(x);
                                                 behavior default:
                                                   
                                               
                                             */
                                             intlist insertsort(intlist x ) 
{
  intlist xi ;
  intlist y ;
  intlist yi ;
  int m ;
  int n ;
  intlist __retres ;
  /*Loc=../../../c/intlist-sort-insert.c:(18,18)*//*sid:1*/
  xi = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-sort-insert.c:(19,19)*//*sid:2*/
  y = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-sort-insert.c:(20,20)*//*sid:3*/
  yi = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-sort-insert.c:(21,21)*//*sid:4*/
  xi = x->next;
  /*Loc=../../../c/intlist-sort-insert.c:(22,22)*//*sid:5*/
  while (xi != (struct char_P *)0) {
    /*Loc=../../../c/intlist-sort-insert.c:(24,24)*//*sid:9*/
    y = x;
    /*Loc=../../../c/intlist-sort-insert.c:(25,25)*//*sid:10*/
    while (y != xi) {
      /*Loc=../../../c/intlist-sort-insert.c:(26,26)*//*sid:15*/
      if (y->data <= xi->data) {
        /*Loc=../../../c/intlist-sort-insert.c:(28,28)*//*sid:16*/
        yi = y->next;
        /*Loc=../../../c/intlist-sort-insert.c:(29,29)*//*sid:17*/
        y = (struct intlist_ *)((struct char_P *)0);
        /*Loc=../../../c/intlist-sort-insert.c:(30,30)*//*sid:18*/
        y = yi;
        /*Loc=../../../c/intlist-sort-insert.c:(31,31)*//*sid:19*/
        yi = (struct intlist_ *)((struct char_P *)0);
      }
      else {
        /*Loc=../../../c/intlist-sort-insert.c:(33,33)*//*sid:20*/
        break;
      }
    }
    /*Loc=../../../c/intlist-sort-insert.c:(35,35)*//*sid:21*/
    m = xi->data;
    /*Loc=../../../c/intlist-sort-insert.c:(36,36)*//*sid:22*/
    while (y != xi) {
      /*Loc=../../../c/intlist-sort-insert.c:(38,38)*//*sid:26*/
      n = y->data;
      /*Loc=../../../c/intlist-sort-insert.c:(39,39)*//*sid:27*/
      y->data = m;
      /*Loc=../../../c/intlist-sort-insert.c:(40,40)*//*sid:28*/
      m = n;
      /*Loc=../../../c/intlist-sort-insert.c:(41,41)*//*sid:29*/
      yi = y->next;
      /*Loc=../../../c/intlist-sort-insert.c:(42,42)*//*sid:30*/
      y = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-sort-insert.c:(43,43)*//*sid:31*/
      y = yi;
      /*Loc=../../../c/intlist-sort-insert.c:(44,44)*//*sid:32*/
      yi = (struct intlist_ *)((struct char_P *)0);
    }
    /*Loc=../../../c/intlist-sort-insert.c:(46,46)*//*sid:33*/
    y = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-sort-insert.c:(47,47)*//*sid:34*/
    xi->data = m;
    /*Loc=../../../c/intlist-sort-insert.c:(48,48)*//*sid:35*/
    yi = xi->next;
    /*Loc=../../../c/intlist-sort-insert.c:(49,49)*//*sid:36*/
    xi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-sort-insert.c:(50,50)*//*sid:37*/
    xi = yi;
    /*Loc=../../../c/intlist-sort-insert.c:(51,51)*//*sid:38*/
    yi = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-sort-insert.c:(53,53)*//*sid:39*/
  __retres = (struct intlist_ *)0;
  /*Loc=../../../c/intlist-sort-insert.c:(53,53)*//*sid:40*/
  return (__retres);
}


