\input texinfo
@c -*-texinfo-*-
@c %**start of header
@setfilename cinv.info
@settitle CINV 0.2
@c @setcontentsaftertitlepage
@c include version.texi
@iftex
@afourpaper
@end iftex
@comment %**end of header

@c This file is part of the CINV tool, released under LGPL
@c license. Please read the COPYING file packaged in the distribution

@setcontentsaftertitlepage

@tex
\global\parskip=0.5ex
\global\baselineskip=3ex
\global\mag=1000
@end tex

@direntry
* cinv: (cinv).  CINV: Tool for Static Analysis of Programs with Lists
@end direntry

@iftex
@finalout
@end iftex

@ifnottex
@node Top, Copying, (dir), (dir)
@top CINV
@end ifnottex

@c Texinfo version 4 or up will be needed to process this into .info files.
@c
@c The edition number is in three places and the month/year in one, all
@c taken from version.texi.  version.texi is created when you configure with
@c --enable-maintainer-mode, and is included in a distribution made with
@c "make dist".

@titlepage
@c  use the new format for titles

@title CINV
@subtitle The CINV tool
@subtitle Edition 0.3, @today{}

@author by Cezara Dragoi and Mihaela Sighireanu
@c Include the Distribution inside the titlepage so
@c that headings are turned off.
@end titlepage

@headings off
@oddheading @thischapter @| @| @thispage
@c @evenheading @thispage @| @| @thissectionname
@everyfooting  @| @| Version: @today{}

@iftex
@page
@vskip 0pt plus 1filll
@end iftex


@ifnothtml
@contents
@end ifnothtml

@menu
* Copying::
* Introduction::
* Examples::
@end menu

@c *******************************************************************
@node Copying, Introduction, Top, Top
@chapter CINV Copying Conditions (LGPL)
@c *******************************************************************

The CINV tool is copyright @copyright{} by the
@uref{http://www.liafa.jussieu.fr/cinv/,CINV project}, and its partners.

This license applies to all files distributed in the CINV tool,
including all source code, libraries, binaries, and documentation.

@include lgpl.texi

@c *******************************************************************
@node Introduction,  Examples, Copying, Top
@chapter Introduction
@c *******************************************************************

The CINV tool provides several @emph{abstract domains} for abstract reachability analysis of programs manipulating
singly linked lists with numerical contents.

The abstract domains of CINV are symbolic representations for specifications which constrain both the shape of the list and the data inside the list. In the present version, three kinds of specifications can be generated: 
(1) specifications relating data, lenghts, and sums of the data of the list (domain LSUM),
(1) specifications relating data, lenghts, and multisets of the data of the list (domain MSET),
(2) specifications relating data, lenghts, and universal properties on the elements of the list (domain UCONS).

The input of CINV is a interprocedural control flow graph (ICFG) in the 
@uref{http://pop-art.inrialpes.fr/people/bjeannet/bjeannet-forge/fixpoint/index.html, Fixpoint library} 
format.
This graph can be obtained from C programs using the 
@uref{http://www.frama-c.com, Frama-C} plugin 
@uref{http://www.liafa.jussieu.fr/celia, Celia}.
Aside the program, CINV has as input the @code{cinv.txt} file which fixes its parameters.

The output is the program annotated by specifications given on files with extension @code{.shp}. 
These files contain a shape value, i.e., a list of constrained heap graphs;
each heap graph is given by tuple built from a graph and a numerical or logical constraint relating the data, the sum of data, and the length of list segments in the graph.

We provide in the following more details on the inputs and output of CINV as well as the presentation of the results obtained when applying CINV on our benchmark.

@menu
* C code::
* Apron encoding::
* Specification logic::           
* Parameters of the analysis::    
* Results::
@end menu

@c -------------------------------------------------------------------
@node C code, Apron encoding,, Introduction
@section C code
@c -------------------------------------------------------------------

@b{THIS PART IS OBSOLTE SINCE REPLACED BY THE CELIA PLUGIN. PLEASE CONSULT CELIA DOCUMENTATION.}

Each example is given as a C function. 
The function has at least one list parameter of type @code{intlist} or its is the @code{main} function.
The C definition of type @code{intlist} corresponds to a singly linked list with an integer data field as follows:
@smallformat
@verbatiminclude ../samples/cspl/intlist.h
@end smallformat

The C code used is a very simple subset of C including pointers.
In this code, all the statements shall be elementary.
@c TODO: add description of CLIM
For instance, composed terms (e.g., @code{x->next->data}) and statements (e.g., @code{x=y} with @code{x} not pointing to @code{NULL}) are not elementary.

The C functions are specified using the logic presented in @ref{Specification logic}.
 
@c -------------------------------------------------------------------
@node Apron encoding, Specification logic, C code, Introduction
@section Spl encoding
@c -------------------------------------------------------------------

@b{THIS PART IS ONLY FOR INTERNAL USE AND SUBJECT SILENT UPDATES.}


The @uref{http://apron.cri.ensmp.fr/library/, Apron library} is intended to be a common interface to various underlying libraries/abstract domains. Since Apron provides only an interface for domains representing numerical values (integers and reals), 
we have to encode lists operations in operations on numerical domains.
The encoding is the following:
@itemize @bullet
@item
Variables of type @code{intlist} are coded by real variables. 
The constant @code{NULL} is encoded by value 0.0.

@item
Data variables are encoded by integer variables.

@item 
The operations on pointers are encoded using operations on real variables as follows:

@multitable @columnfractions .3 .4 .3
@item type @tab C @tab Apron
@item constant @tab @code{NULL} @tab 0.0
@item expression @tab @code{x->data} @tab @code{cast_i,0(x)}
@item expression @tab @code{x->next} @tab @code{cast_f,u(x)}
@item expression @tab @code{x->next} @tab @code{cast_f,d(x)}
@item expression @tab @code{x[i]} @tab @code{x*i}
@item expression @tab @code{\length(x)} @tab @code{cast_l,n(x)}
@item expression @tab @code{\sum(x)} @tab @code{cast_q,0(x)}
@item expression @tab @code{\mset(x)} @tab @code{cast_q,n(x)}
@item statement @tab @code{x->data=expr} @tab @code{x=cast_d,0(expr)}
@item statement @tab @code{x->next=expr} @tab @code{x=cast_d,u(expr)}
@item statement @tab @code{x->next=expr} @tab @code{x=cast_d,d(expr)}
@item statement @tab @code{x[i]=expr} @tab @code{x=(expr) / i}
@item statement @tab @code{x=malloc(size);} @tab @code{x=sqrt_f,n(size)}
@item statement @tab @code{free(x);} @tab @code{x=sqrt_f,n(size)}
@end multitable

@item
All statements are elementary:
 (1) the only terms used on pointer variables are @code{x}, @code{x->data}, and @code{x->next},
 (2) the statements have as left hand side one of the terms above, and 
 (3) when left values @code{x} and @code{x->next} are assigned, they have to be @code{NULL}.

@item 
The specification properties (see @ref{Specification logic}) of the code are encoded into Apron constraints as folloxs:
@c MS: change all this to introduce flexibility on variables' name
@c assume take a boolean expression where the atomic predicates are:

@table @kbd
@item @math{acyclic(x)}
@math{x > 0.0}

@item @math{cyclic(x)}
@math{cast_f,n(x) > x}

@item @math{x==NULL}
@math{x == 0.0}

@item @math{x!=NULL}
@math{x != 0.0}

@item @math{disjoint(x,y)}
@math{x <> y}

@item @math{isomorph(x,y)}
@math{x == y}

@item @math{reach(x,y)}
@math{x > y}

@c - constraints on length(x) and sum(x) and mset(x) encoded with tcons

@end table
@end itemize



@c -------------------------------------------------------------------
@node Specification logic, Parameters of the analysis, Apron encoding, Introduction
@section Specification logic
@c -------------------------------------------------------------------

The initial constraint on the program analysed is given in a logic which is a restriction of the CSL logic defined in [Bouajjani and al. CONCUR-09].
This logic is a multi-sorted first order logic with reachability predicates.
More precisely, in this logic one can use the following terms:
@table @kbd
@item len[n]
the length of the heap segment stating from node @code{n}, i.e., the number of edges of the segment.

@item data[n]
the data stored in the first element of the heap segment starting in the node @code{n}.

@item sum[n]
the sum of the data stored in the heap segment starting from node @code{n} except @code{n} itself.

@item mstl[n]
the multiset of data stored in the heap segment starting from node @code{n} except @code{n} itself.

@item mshd[n]
is the term used to represent @code{data[n]} in the multiset constraints.
@end table

The atomic constraints of the logic are the following:

@table @kbd
@item x(n)
variable @code{x} is labeling a node of a heap called @code{n}.

@item expr op 0 
where op in @math{=,!=,<=,>=,!=,<,>} is a linear constraints on terms.

@item acyclic(x)
variable @code{x} labels a node from which starts a segment which is acyclic.

@item reach(x,y)
variable @code{x} labels a node from which starts a segment which reaches another node labeled by @code{y}.

@item disjoint(x,y)
variable @code{x} labels a node from which starts a segment which is disjoint from (does not share nodes with) the list segment which starting node is labeled by @code{y}.

@end table


@c -------------------------------------------------------------------
@node Parameters of the analysis, Results, Specification logic, Introduction
@section Parameters of the analysis
@c -------------------------------------------------------------------

The analysis done by the CINV tool is parametrized by the following inputs:

@itemize @bullet
@item @emph{Domain:}
@anchor{Domains}
The abstract domain used to represent heap segments. This domain is used by the global domain of @code{Shapes}. The following domains are implemented in CINV:
@table @kbd
@item LSUM-PRD
the domain of sums over heap segments which is a Cartesian product of a domain for lengths of segments and a domain for data of segments.

@item LSUM-REL
the domain of sums over heap segments where lengths and data are put together.

@item MSET-PRD
the domain of multisets over heap segments which is a Cartesian product of a domain for lengths of segments, a domain for data of segments, and a multiset domain.

@item MSET-REL
the domain of multisets over heap segments where lengths and data are put together.

@item UCONS
the domain of universally constrained heap segments; this domain is parametrized by the set of patterns used by the universally quantified constraints. 
Actually, for efficiency reasons, the following patterns are implemented:
@table @kbd
@item P11
@math{\forall y \in n \Rightarrow ...}
@item P21
@math{\forall y1 \in n, y2 \in m, y1=y2 \Rightarrow ...}
@item P12
@math{\forall y1,y2 \in n, y1<=y2 \Rightarrow ...}
@item P13
@math{\forall y1,y2,y3 \in n, y1 <_1 y2 <_1 y3 \Rightarrow ...}
@end table
@end table

@item @emph{Number of simple nodes:}
The computation of the post abstract transformer is parameterized by the maximum number of simple nodes (nodes not labeled by a program variable or representing a sharing point) in the heap graph. 
In CINV, this number is obtained from the following two parameters:
@table @kbd
@item max_anon
the maximum number of simple nodes in a heap segment, and

@item segm_anon
the number of segments shall divide the number of simple nodes.
@end table
These two parameters shall be given in the file @code{cinv.txt} in the directory chosen for the execution of CINV.
@end itemize


@c -------------------------------------------------------------------
@node Results, , Parameters of the analysis, Introduction
@section Results
@c -------------------------------------------------------------------

@b{THESE RESULTS ARE NOW OBSOLETE. PLEASE CONSULT THE 
@url{http://www.liafa.jussieu.fr/celia, CELIA plugin} site.}

The results are given for each domain and each parameter using:
@itemize
@item @emph{Log file}:
is a directory in @code{sample/log} containing a log file and the files storing the shapes generated
@item @emph{Constraint}:
is the most interesting constraint synthesized by the analysis; this constraint is given in the specification language (see @ref{Specification logic}).
@end itemize
In the HTML version of this manual, it is possible to browse the log directory.
The present time and memory performances have been obtained on an Intel 686 2GHz and 1 Go of RAM.

@c ===================================================================
@node Examples, , Introduction, Top
@chapter Examples
@c ===================================================================

@menu
* Computing on data::
* Initializing data::
* Changing data::
* Changing structure::
@end menu

@include samples.texi 


@bye
