/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
typedef unsigned int size_t;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@ behavior default:
      assigns \at(\result,Post) \from __size;  */
extern  __attribute__((__nothrow__)) struct char_P *malloc(size_t __size )  __attribute__((
__malloc__)) ;
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
intlist fold_clone(intlist x ) ;
/*Loc=../../../c/intlist-fold-clone.c(9,9)*//*@ requires //id:67
                                                         acyclic{Here}(x);
                                                behavior default:
                                                  
                                              
                                            */
                                            intlist fold_clone(intlist x ) 
{
  intlist xi ;
  intlist y ;
  intlist yi ;
  intlist z ;
  /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:1*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:2*/
    z = (struct intlist_ *)((struct char_P *)0);
    /*effects: z <- */
    /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:3*/
    yi = z;
    /*effects: yi <- */
    /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:4*/
    y = yi;
    /*effects: y <- */
    /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:5*/
    xi = y;
    /*effects: xi <- */
  }
  /*Loc=../../../c/intlist-fold-clone.c:(12,12)*//*sid:6*/
  xi = x;
  /*Loc=../../../c/intlist-fold-clone.c:(13,13)*//*sid:7*/
  while (xi != (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold-clone.c:(14,14)*//*sid:11*/
    z = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-fold-clone.c:(15,15)*//*sid:12*/
    z->data = xi->data;
    /*Loc=../../../c/intlist-fold-clone.c:(16,16)*//*sid:13*/
    z->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-clone.c:(17,17)*//*sid:15*/
    if (y == (struct char_P *)0) {
      /*Loc=../../../c/intlist-fold-clone.c:(18,18)*//*sid:16*/
      y = z;
    }
    else {
      /*Loc=../../../c/intlist-fold-clone.c:(20,20)*//*sid:17*/
      yi->next = z;
    }
    /*Loc=../../../c/intlist-fold-clone.c:(21,21)*//*sid:18*/
    yi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-clone.c:(22,22)*//*sid:19*/
    yi = z;
    /*Loc=../../../c/intlist-fold-clone.c:(23,23)*//*sid:20*/
    z = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-clone.c:(24,24)*//*sid:21*/
    z = xi->next;
    /*Loc=../../../c/intlist-fold-clone.c:(25,25)*//*sid:22*/
    xi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-clone.c:(26,26)*//*sid:23*/
    xi = z;
    /*Loc=../../../c/intlist-fold-clone.c:(27,27)*//*sid:24*/
    z = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-fold-clone.c:(29,29)*//*sid:25*/
  yi = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-fold-clone.c:(30,30)*//*sid:26*/
  return (y);
}


