
all:
	$(CINV)/bin/frama-c-Celia.byte -celia -celia-cinv-opt lsum.prop $(CINV)/samples/c/intlist-fold-clone.c $(CINV)/samples/c/intlist-fold-split_rec.c $(CINV)/samples/c/intlist-fold2-merge.c $(CINV)/samples/c/intlist-sort-merge.c

clean:
	rm *.shp pan* *.txt
