/* Generated by Frama-C */
struct struct_intlist__xP {
   struct intlist_ *struct_intlist__xM ;
};
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
typedef unsigned int size_t;
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
intlist fold_clone(intlist x_2 ) ;
intlist fold2_merge(intlist x_0 , intlist y ) ;
void split(intlist x_1 , struct struct_intlist__xP *l1 ,
           struct struct_intlist__xP *l2 ) ;
/*Loc=../../../c/intlist-sort-merge.c(12,12)*//*@ requires //id:268
                                                           acyclic{Here}(x);
                                                  behavior default:
                                                    
                                                
                                              */
                                              intlist mergesort(intlist x ) 
{
  intlist r ;
  intlist tmp ;
  struct struct_intlist__xP *l1_0 ;
  struct struct_intlist__xP *l2_0 ;
  /*Loc=../../../c/intlist-sort-merge.c:(14,14)*//*sid:1*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-sort-merge.c:(14,14)*//*sid:2*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*effects: tmp <- */
    /*Loc=../../../c/intlist-sort-merge.c:(14,14)*//*sid:3*/
    r = tmp;
    /*effects: r <- */
  }
  /*Loc=../../../c/intlist-sort-merge.c:(15,15)*//*sid:5*/
  if (x != (struct char_P *)0) {
    /*Loc=../../../c/intlist-sort-merge.c:(16,16)*//*sid:6*/
    tmp = x->next;
    /*Loc=../../../c/intlist-sort-merge.c:(17,17)*//*sid:8*/
    if (tmp == (struct char_P *)0) {
      /*Loc=../../../c/intlist-sort-merge.c:(18,18)*//*sid:9*/
      r = fold_clone(x);
    }
    else {
      /*Loc=../../../c/intlist-sort-merge.c:(21,21)*//*sid:10*/
      tmp = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-sort-merge.c:(22,22)*//*sid:11*/
      l1_0->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-sort-merge.c:(23,23)*//*sid:12*/
      l2_0->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-sort-merge.c:(24,24)*//*sid:13*/
      split(x,l1_0,l2_0);
      /*Loc=../../../c/intlist-sort-merge.c:(25,25)*//*sid:14*/
      tmp = mergesort(l1_0->struct_intlist__xM);
      /*Loc=../../../c/intlist-sort-merge.c:(26,26)*//*sid:15*/
      l1_0->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-sort-merge.c:(26,26)*//*sid:16*/
      l1_0->struct_intlist__xM = tmp;
      /*Loc=../../../c/intlist-sort-merge.c:(26,26)*//*sid:17*/
      tmp = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-sort-merge.c:(27,27)*//*sid:18*/
      tmp = mergesort(l2_0->struct_intlist__xM);
      /*Loc=../../../c/intlist-sort-merge.c:(28,28)*//*sid:19*/
      l2_0->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-sort-merge.c:(28,28)*//*sid:20*/
      l2_0->struct_intlist__xM = tmp;
      /*Loc=../../../c/intlist-sort-merge.c:(28,28)*//*sid:21*/
      tmp = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-sort-merge.c:(29,29)*//*sid:22*/
      tmp = fold2_merge(l1_0->struct_intlist__xM,l2_0->struct_intlist__xM);
      /*Loc=../../../c/intlist-sort-merge.c:(30,30)*//*sid:23*/
      l1_0->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-sort-merge.c:(30,30)*//*sid:24*/
      l2_0->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-sort-merge.c:(31,31)*//*sid:25*/
      r = tmp;
      /*Loc=../../../c/intlist-sort-merge.c:(31,31)*//*sid:26*/
      tmp = (struct intlist_ *)((struct char_P *)0);
    }
  }
  /*Loc=../../../c/intlist-sort-merge.c:(34,34)*//*sid:28*/
  return (r);
}

/*@ behavior default:
      assigns \at(\result,Post) \from __size;  */
extern  __attribute__((__nothrow__)) struct char_P *malloc(size_t __size )  __attribute__((
__malloc__)) ;
/*Loc=../../../c/intlist-fold2-merge.c(10,10)*//*@ requires //id:201
                                                            ((acyclic{
                                                              Here}(x_0)
                                                             ∧
                                                             acyclic{Here}(y))
                                                            ∧
                                                            disjoint{
                                                            Here}(x_0, y));
                                                   behavior default:
                                                     
                                                 
                                               */
                                               intlist fold2_merge(intlist x_0 ,
                                                                   intlist y ) 
{
  intlist r_0 ;
  intlist ri ;
  intlist xi ;
  intlist yi ;
  intlist tmp_0 ;
  int v ;
  /*Loc=../../../c/intlist-fold2-merge.c:(13,13)*//*sid:29*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-fold2-merge.c:(13,13)*//*sid:30*/
    tmp_0 = (struct intlist_ *)((struct char_P *)0);
    /*effects: tmp_0 <- */
    /*Loc=../../../c/intlist-fold2-merge.c:(13,13)*//*sid:31*/
    yi = tmp_0;
    /*effects: yi <- */
    /*Loc=../../../c/intlist-fold2-merge.c:(13,13)*//*sid:32*/
    xi = yi;
    /*effects: xi <- */
    /*Loc=../../../c/intlist-fold2-merge.c:(13,13)*//*sid:33*/
    ri = xi;
    /*effects: ri <- */
    /*Loc=../../../c/intlist-fold2-merge.c:(13,13)*//*sid:34*/
    r_0 = ri;
    /*effects: r_0 <- */
  }
  /*Loc=../../../c/intlist-fold2-merge.c:(14,14)*//*sid:35*/
  xi = x_0;
  /*Loc=../../../c/intlist-fold2-merge.c:(15,15)*//*sid:36*/
  yi = y;
  /*Loc=../../../c/intlist-fold2-merge.c:(16,16)*//*sid:37*/
  while (1) {
    /*Loc=../../../c/intlist-fold2-merge.c:(16,16)*//*sid:39*/
    if (xi != (struct char_P *)0) {
      /*Loc=../../../c/intlist-fold2-merge.c:(16,16)*//*sid:41*/
      if (! (yi != (struct char_P *)0)) {
        /*Loc=../../../c/intlist-fold2-merge.c:(16,16)*//*sid:42*/
        break;
      }
    }
    else { /*Loc=../../../c/intlist-fold2-merge.c:(16,16)*//*sid:43*/ break;
    }
    /*Loc=../../../c/intlist-fold2-merge.c:(17,17)*//*sid:45*/
    if (xi->data < yi->data) {
      /*Loc=../../../c/intlist-fold2-merge.c:(18,18)*//*sid:46*/
      v = xi->data;
      /*Loc=../../../c/intlist-fold2-merge.c:(19,19)*//*sid:47*/
      tmp_0 = xi->next;
      /*Loc=../../../c/intlist-fold2-merge.c:(20,20)*//*sid:48*/
      xi = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold2-merge.c:(21,21)*//*sid:49*/
      xi = tmp_0;
      /*Loc=../../../c/intlist-fold2-merge.c:(22,22)*//*sid:50*/
      tmp_0 = (struct intlist_ *)((struct char_P *)0);
    }
    else {
      /*Loc=../../../c/intlist-fold2-merge.c:(24,24)*//*sid:51*/
      v = yi->data;
      /*Loc=../../../c/intlist-fold2-merge.c:(25,25)*//*sid:52*/
      tmp_0 = yi->next;
      /*Loc=../../../c/intlist-fold2-merge.c:(26,26)*//*sid:53*/
      yi = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold2-merge.c:(27,27)*//*sid:54*/
      yi = tmp_0;
      /*Loc=../../../c/intlist-fold2-merge.c:(28,28)*//*sid:55*/
      tmp_0 = (struct intlist_ *)((struct char_P *)0);
    }
    /*Loc=../../../c/intlist-fold2-merge.c:(31,31)*//*sid:56*/
    tmp_0 = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-fold2-merge.c:(32,32)*//*sid:57*/
    tmp_0->data = v;
    /*Loc=../../../c/intlist-fold2-merge.c:(33,33)*//*sid:58*/
    tmp_0->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(34,34)*//*sid:60*/
    if (r_0 == (struct char_P *)0) {
      /*Loc=../../../c/intlist-fold2-merge.c:(35,35)*//*sid:61*/
      r_0 = tmp_0;
      /*Loc=../../../c/intlist-fold2-merge.c:(36,36)*//*sid:62*/
      ri = tmp_0;
    }
    else {
      /*Loc=../../../c/intlist-fold2-merge.c:(38,38)*//*sid:63*/
      ri->next = tmp_0;
      /*Loc=../../../c/intlist-fold2-merge.c:(39,39)*//*sid:64*/
      ri = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold2-merge.c:(40,40)*//*sid:65*/
      ri = tmp_0;
    }
    /*Loc=../../../c/intlist-fold2-merge.c:(42,42)*//*sid:66*/
    tmp_0 = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-fold2-merge.c:(44,44)*//*sid:67*/
  while (xi != (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold2-merge.c:(46,46)*//*sid:71*/
    tmp_0 = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-fold2-merge.c:(47,47)*//*sid:72*/
    tmp_0->data = xi->data;
    /*Loc=../../../c/intlist-fold2-merge.c:(48,48)*//*sid:73*/
    tmp_0->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(49,49)*//*sid:75*/
    if (r_0 == (struct char_P *)0) {
      /*Loc=../../../c/intlist-fold2-merge.c:(50,50)*//*sid:76*/
      r_0 = tmp_0;
      /*Loc=../../../c/intlist-fold2-merge.c:(51,51)*//*sid:77*/
      ri = tmp_0;
    }
    else {
      /*Loc=../../../c/intlist-fold2-merge.c:(53,53)*//*sid:78*/
      ri->next = tmp_0;
      /*Loc=../../../c/intlist-fold2-merge.c:(54,54)*//*sid:79*/
      ri = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold2-merge.c:(55,55)*//*sid:80*/
      ri = tmp_0;
    }
    /*Loc=../../../c/intlist-fold2-merge.c:(57,57)*//*sid:81*/
    tmp_0 = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(58,58)*//*sid:82*/
    tmp_0 = xi->next;
    /*Loc=../../../c/intlist-fold2-merge.c:(59,59)*//*sid:83*/
    xi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(60,60)*//*sid:84*/
    xi = tmp_0;
    /*Loc=../../../c/intlist-fold2-merge.c:(61,61)*//*sid:85*/
    tmp_0 = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-fold2-merge.c:(63,63)*//*sid:86*/
  while (yi != (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold2-merge.c:(64,64)*//*sid:90*/
    tmp_0 = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-fold2-merge.c:(65,65)*//*sid:91*/
    tmp_0->data = yi->data;
    /*Loc=../../../c/intlist-fold2-merge.c:(66,66)*//*sid:92*/
    tmp_0->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(67,67)*//*sid:94*/
    if (r_0 == (struct char_P *)0) {
      /*Loc=../../../c/intlist-fold2-merge.c:(68,68)*//*sid:95*/
      r_0 = tmp_0;
      /*Loc=../../../c/intlist-fold2-merge.c:(69,69)*//*sid:96*/
      ri = tmp_0;
    }
    else {
      /*Loc=../../../c/intlist-fold2-merge.c:(71,71)*//*sid:97*/
      ri->next = tmp_0;
      /*Loc=../../../c/intlist-fold2-merge.c:(72,72)*//*sid:98*/
      ri = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold2-merge.c:(73,73)*//*sid:99*/
      ri = tmp_0;
    }
    /*Loc=../../../c/intlist-fold2-merge.c:(75,75)*//*sid:100*/
    tmp_0 = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(76,76)*//*sid:101*/
    tmp_0 = yi->next;
    /*Loc=../../../c/intlist-fold2-merge.c:(77,77)*//*sid:102*/
    yi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-merge.c:(78,78)*//*sid:103*/
    yi = tmp_0;
    /*Loc=../../../c/intlist-fold2-merge.c:(79,79)*//*sid:104*/
    tmp_0 = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-fold2-merge.c:(81,81)*//*sid:105*/
  ri = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-fold2-merge.c:(82,82)*//*sid:106*/
  return (r_0);
}

/*Loc=../../../c/intlist-fold-split_rec.c(12,12)*//*@ requires //id:134
                                                               acyclic{
                                                               Here}(x_1);
                                                      behavior default:
                                                        
                                                    
                                                  */
                                                  void split(intlist x_1 ,
                                                             struct struct_intlist__xP *l1 ,
                                                             struct struct_intlist__xP *l2 ) 
{
  intlist tmp_1 ;
  intlist nxt ;
  intlist ll1 ;
  intlist ll2 ;
  /*Loc=../../../c/intlist-fold-split_rec.c:(16,16)*//*sid:108*/
  if (x_1 == (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold-split_rec.c:(17,17)*//*sid:109*/
    l1->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-split_rec.c:(18,18)*//*sid:110*/
    l2->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-split_rec.c:(19,19)*//*sid:169*/
    goto return_label;
  }
  /*Loc=../../../c/intlist-fold-split_rec.c:(22,22)*//*sid:113*/
  nxt = x_1->next;
  /*Loc=../../../c/intlist-fold-split_rec.c:(23,23)*//*sid:114*/
  ll1 = (intlist )malloc(sizeof(struct intlist_ ));
  /*Loc=../../../c/intlist-fold-split_rec.c:(24,24)*//*sid:115*/
  ll1->data = x_1->data;
  /*Loc=../../../c/intlist-fold-split_rec.c:(25,25)*//*sid:116*/
  ll1->next = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-fold-split_rec.c:(27,27)*//*sid:118*/
  if (nxt == (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold-split_rec.c:(28,28)*//*sid:119*/
    l1->struct_intlist__xM = ll1;
    /*Loc=../../../c/intlist-fold-split_rec.c:(29,29)*//*sid:120*/
    l2->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-split_rec.c:(30,30)*//*sid:121*/
    { /*undefined sequence*/ 
      /*Loc=../../../c/intlist-fold-split_rec.c:(30,30)*//*sid:122*/
      ll1 = (struct intlist_ *)((struct char_P *)0);
      /*effects: ll1 <- */
      /*Loc=../../../c/intlist-fold-split_rec.c:(30,30)*//*sid:123*/
      nxt = ll1;
      /*effects: nxt <- */
    }
    /*Loc=../../../c/intlist-fold-split_rec.c:(31,31)*//*sid:170*/
    goto return_label;
  }
  /*Loc=../../../c/intlist-fold-split_rec.c:(34,34)*//*sid:126*/
  ll2 = (intlist )malloc(sizeof(struct intlist_ ));
  /*Loc=../../../c/intlist-fold-split_rec.c:(35,35)*//*sid:127*/
  ll2->data = nxt->data;
  /*Loc=../../../c/intlist-fold-split_rec.c:(36,36)*//*sid:128*/
  ll2->next = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-fold-split_rec.c:(37,37)*//*sid:129*/
  tmp_1 = nxt->next;
  /*Loc=../../../c/intlist-fold-split_rec.c:(39,39)*//*sid:130*/
  split(tmp_1,l1,l2);
  /*Loc=../../../c/intlist-fold-split_rec.c:(41,41)*//*sid:131*/
  ll1->next = l1->struct_intlist__xM;
  /*Loc=../../../c/intlist-fold-split_rec.c:(42,42)*//*sid:132*/
  ll2->next = l2->struct_intlist__xM;
  /*Loc=../../../c/intlist-fold-split_rec.c:(43,43)*//*sid:133*/
  l1->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-fold-split_rec.c:(43,43)*//*sid:134*/
  l1->struct_intlist__xM = ll1;
  /*Loc=../../../c/intlist-fold-split_rec.c:(44,44)*//*sid:135*/
  l2->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-fold-split_rec.c:(44,44)*//*sid:136*/
  l2->struct_intlist__xM = ll2;
  /*Loc=../../../c/intlist-fold-split_rec.c:(46,46)*//*sid:137*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-fold-split_rec.c:(46,46)*//*sid:138*/
    nxt = (struct intlist_ *)((struct char_P *)0);
    /*effects: nxt <- */
    /*Loc=../../../c/intlist-fold-split_rec.c:(46,46)*//*sid:139*/
    tmp_1 = nxt;
    /*effects: tmp_1 <- */
    /*Loc=../../../c/intlist-fold-split_rec.c:(46,46)*//*sid:140*/
    ll2 = tmp_1;
    /*effects: ll2 <- */
    /*Loc=../../../c/intlist-fold-split_rec.c:(46,46)*//*sid:141*/
    ll1 = ll2;
    /*effects: ll1 <- */
  }
  /*Loc=../../../c/intlist-fold-split_rec.c:(48,48)*/return_label: /* internal */ 
  /*sid:171*/
  return;
}

/*Loc=../../../c/intlist-fold-clone.c(9,9)*//*@ requires //id:67
                                                         acyclic{Here}(x_2);
                                                behavior default:
                                                  
                                              
                                            */
                                            intlist fold_clone(intlist x_2 ) 
{
  intlist xi_0 ;
  intlist y_0 ;
  intlist yi_0 ;
  intlist z ;
  /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:143*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:144*/
    z = (struct intlist_ *)((struct char_P *)0);
    /*effects: z <- */
    /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:145*/
    yi_0 = z;
    /*effects: yi_0 <- */
    /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:146*/
    y_0 = yi_0;
    /*effects: y_0 <- */
    /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:147*/
    xi_0 = y_0;
    /*effects: xi_0 <- */
  }
  /*Loc=../../../c/intlist-fold-clone.c:(12,12)*//*sid:148*/
  xi_0 = x_2;
  /*Loc=../../../c/intlist-fold-clone.c:(13,13)*//*sid:149*/
  while (xi_0 != (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold-clone.c:(14,14)*//*sid:153*/
    z = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-fold-clone.c:(15,15)*//*sid:154*/
    z->data = xi_0->data;
    /*Loc=../../../c/intlist-fold-clone.c:(16,16)*//*sid:155*/
    z->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-clone.c:(17,17)*//*sid:157*/
    if (y_0 == (struct char_P *)0) {
      /*Loc=../../../c/intlist-fold-clone.c:(18,18)*//*sid:158*/
      y_0 = z;
    }
    else {
      /*Loc=../../../c/intlist-fold-clone.c:(20,20)*//*sid:159*/
      yi_0->next = z;
    }
    /*Loc=../../../c/intlist-fold-clone.c:(21,21)*//*sid:160*/
    yi_0 = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-clone.c:(22,22)*//*sid:161*/
    yi_0 = z;
    /*Loc=../../../c/intlist-fold-clone.c:(23,23)*//*sid:162*/
    z = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-clone.c:(24,24)*//*sid:163*/
    z = xi_0->next;
    /*Loc=../../../c/intlist-fold-clone.c:(25,25)*//*sid:164*/
    xi_0 = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-clone.c:(26,26)*//*sid:165*/
    xi_0 = z;
    /*Loc=../../../c/intlist-fold-clone.c:(27,27)*//*sid:166*/
    z = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-fold-clone.c:(29,29)*//*sid:167*/
  yi_0 = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-fold-clone.c:(30,30)*//*sid:168*/
  return (y_0);
}


