/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
/*@ behavior default:
      assigns \nothing;  */
struct char_P *malloc(unsigned int size ) ;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
void map_initFibo(intlist head ) ;
/*Loc=../../../c/intlist-map-initFibo.c(9,9)*//*@ requires //id:67
                                                           acyclic{Here}
                                                           (head);
                                                  behavior default:
                                                    
                                                
                                              */
                                              void map_initFibo(intlist head ) 
{
  int m1 ;
  int m2 ;
  intlist xi ;
  intlist tmp ;
  /*Loc=../../../c/intlist-map-initFibo.c:(10,10)*//*sid:1*/
  m1 = 1;
  /*Loc=../../../c/intlist-map-initFibo.c:(11,11)*//*sid:2*/
  m2 = 0;
  /*Loc=../../../c/intlist-map-initFibo.c:(13,13)*//*sid:3*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-map-initFibo.c:(13,13)*//*sid:4*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*effects: tmp <- */
    /*Loc=../../../c/intlist-map-initFibo.c:(13,13)*//*sid:5*/
    xi = tmp;
    /*effects: xi <- */
  }
  /*Loc=../../../c/intlist-map-initFibo.c:(14,14)*//*sid:6*/
  xi = head;
  /*Loc=../../../c/intlist-map-initFibo.c:(15,15)*//*sid:7*/
  while (xi != (struct char_P *)0) {
    /*Loc=../../../c/intlist-map-initFibo.c:(16,16)*//*sid:11*/
    xi->data = m1 + m2;
    /*Loc=../../../c/intlist-map-initFibo.c:(17,17)*//*sid:12*/
    m1 = m2;
    /*Loc=../../../c/intlist-map-initFibo.c:(18,18)*//*sid:13*/
    m2 = xi->data;
    /*Loc=../../../c/intlist-map-initFibo.c:(19,19)*//*sid:14*/
    tmp = xi->next;
    /*Loc=../../../c/intlist-map-initFibo.c:(20,20)*//*sid:15*/
    xi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-map-initFibo.c:(21,21)*//*sid:16*/
    xi = tmp;
    /*Loc=../../../c/intlist-map-initFibo.c:(22,22)*//*sid:17*/
    tmp = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-map-initFibo.c:(24,24)*//*sid:19*/
  return;
}


