/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
/*@ behavior default:
      assigns \nothing;  */
struct char_P *malloc(unsigned int size ) ;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
int empty(intlist head ) ;
/*Loc=../../../c/intlist-lib-empty.c(7,7)*//*@ requires //id:67
                                                        acyclic{Here}(head);
                                               behavior default:
                                                 
                                             
                                           */
                                           int empty(intlist head ) 
{
  int __retres ;
  /*Loc=../../../c/intlist-lib-empty.c:(8,8)*//*sid:2*/
  if (head == (struct char_P *)0) {
    /*Loc=../../../c/intlist-lib-empty.c:(9,9)*//*sid:3*/
    __retres = 0;
    /*Loc=../../../c/intlist-lib-empty.c:(9,9)*//*sid:6*/
    goto return_label;
  }
  /*Loc=../../../c/intlist-lib-empty.c:(10,10)*//*sid:5*/
  __retres = 1;
  /*Loc=../../../c/intlist-lib-empty.c:(10,10)*/return_label: /* internal */ 
  /*sid:7*/
  return (__retres);
}


