/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
typedef unsigned int size_t;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@ behavior default:
      assigns \at(\result,Post) \from __size;  */
extern  __attribute__((__nothrow__)) struct char_P *malloc(size_t __size )  __attribute__((
__malloc__)) ;
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
intlist fold_copyGe5(intlist x ) ;
/*Loc=../../../c/intlist-fold-copyGe5.c(9,9)*//*@ requires //id:67
                                                           acyclic{Here}(x);
                                                  behavior default:
                                                    
                                                
                                              */
                                              intlist fold_copyGe5(intlist x ) 
{
  intlist z ;
  intlist y ;
  intlist xi ;
  /*Loc=../../../c/intlist-fold-copyGe5.c:(11,11)*//*sid:1*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-fold-copyGe5.c:(11,11)*//*sid:2*/
    xi = (struct intlist_ *)((struct char_P *)0);
    /*effects: xi <- */
    /*Loc=../../../c/intlist-fold-copyGe5.c:(11,11)*//*sid:3*/
    y = xi;
    /*effects: y <- */
    /*Loc=../../../c/intlist-fold-copyGe5.c:(11,11)*//*sid:4*/
    z = y;
    /*effects: z <- */
  }
  /*Loc=../../../c/intlist-fold-copyGe5.c:(12,12)*//*sid:5*/
  xi = x;
  /*Loc=../../../c/intlist-fold-copyGe5.c:(13,13)*//*sid:6*/
  while (xi != (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold-copyGe5.c:(14,14)*//*sid:11*/
    if (xi->data >= 5) {
      /*Loc=../../../c/intlist-fold-copyGe5.c:(15,15)*//*sid:12*/
      z = (intlist )malloc(sizeof(struct intlist_ ));
      /*Loc=../../../c/intlist-fold-copyGe5.c:(16,16)*//*sid:13*/
      z->data = xi->data;
      /*Loc=../../../c/intlist-fold-copyGe5.c:(17,17)*//*sid:14*/
      z->next = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold-copyGe5.c:(18,18)*//*sid:15*/
      z->next = y;
      /*Loc=../../../c/intlist-fold-copyGe5.c:(19,19)*//*sid:16*/
      y = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold-copyGe5.c:(20,20)*//*sid:17*/
      y = z;
      /*Loc=../../../c/intlist-fold-copyGe5.c:(21,21)*//*sid:18*/
      z = (struct intlist_ *)((struct char_P *)0);
    }
    /*Loc=../../../c/intlist-fold-copyGe5.c:(23,23)*//*sid:20*/
    z = xi->next;
    /*Loc=../../../c/intlist-fold-copyGe5.c:(24,24)*//*sid:21*/
    xi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-copyGe5.c:(25,25)*//*sid:22*/
    xi = z;
    /*Loc=../../../c/intlist-fold-copyGe5.c:(26,26)*//*sid:23*/
    z = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-fold-copyGe5.c:(28,28)*//*sid:24*/
  return (y);
}


