/* Generated by Frama-C */
struct struct_intlist__xP {
   struct intlist_ *struct_intlist__xM ;
};
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
typedef unsigned int size_t;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@ behavior default:
      assigns \at(\result,Post) \from __size;  */
extern  __attribute__((__nothrow__)) struct char_P *malloc(size_t __size )  __attribute__((
__malloc__)) ;
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
intlist fold_concat3(intlist x , intlist y , intlist h ) ;
/*Loc=../../../cc/intlist-main-quick3-concat3.c(50,50)*//*@ requires 
                                                              //id:1
                                                              acyclic{
                                                              Here}(a);
                                                            behavior default:
                                                              
                                                          
                                                        */
                                                        intlist quicksort(
intlist a ) 
{
  struct struct_intlist__xP *left ;
  struct struct_intlist__xP *right ;
  intlist pivot ;
  intlist res ;
  intlist start ;
  intlist tmp ;
  int d ;
  int l ;
  intlist xis ;
  intlist ys ;
  intlist tmps ;
  intlist tmp_3 ;
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(58,58)*//*sid:2*/
  if (a == (struct char_P *)0) {
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(59,59)*//*sid:3*/
    res = (struct intlist_ *)((struct char_P *)0);
  }
  else {
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(61,61)*//*sid:4*/
    start = a->next;
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(62,62)*//*sid:6*/
    if (start == (struct char_P *)0) {
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(64,64)*//*sid:7*/
      res = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(65,65)*//*sid:8*/
      res = (intlist )malloc(sizeof(struct intlist_ ));
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(66,66)*//*sid:9*/
      res->data = a->data;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(67,67)*//*sid:10*/
      res->next = (struct intlist_ *)((struct char_P *)0);
    }
    else {
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(71,71)*//*sid:11*/
      d = a->data;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(72,72)*//*sid:12*/
      l = 1;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(73,73)*//*sid:13*/
      pivot = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(74,74)*//*sid:14*/
      pivot = (intlist )malloc(sizeof(struct intlist_ ));
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(75,75)*//*sid:15*/
      pivot->next = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(76,76)*//*sid:16*/
      pivot->data = d;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(77,77)*//*sid:17*/
      { /*undefined sequence*/ 
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(77,77)*//*sid:18*/
        tmps = (struct intlist_ *)((struct char_P *)0);
        /*effects: tmps <- */
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(77,77)*//*sid:19*/
        ys = tmps;
        /*effects: ys <- */
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(77,77)*//*sid:20*/
        xis = ys;
        /*effects: xis <- */
      }
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(78,78)*//*sid:21*/
      xis = start;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(79,79)*//*sid:22*/
      left->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(80,80)*//*sid:23*/
      right->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(81,81)*//*sid:24*/
      while (xis != (struct char_P *)0) {
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(82,82)*//*sid:28*/
        ys = (intlist )malloc(sizeof(struct intlist_ ));
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(83,83)*//*sid:29*/
        ys->data = xis->data;
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(84,84)*//*sid:30*/
        ys->next = (struct intlist_ *)((struct char_P *)0);
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(85,85)*//*sid:31*/
        tmps = xis->next;
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(86,86)*//*sid:32*/
        xis = (struct intlist_ *)((struct char_P *)0);
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(87,87)*//*sid:33*/
        xis = tmps;
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(88,88)*//*sid:34*/
        tmps = (struct intlist_ *)((struct char_P *)0);
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(89,89)*//*sid:36*/
        if (ys->data <= d) {
          /*Loc=../../../cc/intlist-main-quick3-concat3.c:(90,90)*//*sid:37*/
          ys->next = left->struct_intlist__xM;
          /*Loc=../../../cc/intlist-main-quick3-concat3.c:(91,91)*//*sid:38*/
          left->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
          /*Loc=../../../cc/intlist-main-quick3-concat3.c:(92,92)*//*sid:39*/
          left->struct_intlist__xM = ys;
        }
        else {
          /*Loc=../../../cc/intlist-main-quick3-concat3.c:(94,94)*//*sid:40*/
          ys->next = right->struct_intlist__xM;
          /*Loc=../../../cc/intlist-main-quick3-concat3.c:(95,95)*//*sid:41*/
          right->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
          /*Loc=../../../cc/intlist-main-quick3-concat3.c:(96,96)*//*sid:42*/
          right->struct_intlist__xM = ys;
        }
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(98,98)*//*sid:43*/
        ys = (struct intlist_ *)((struct char_P *)0);
      }
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(100,100)*//*sid:44*/
      start = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(101,101)*//*sid:45*/
      l = 1;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(102,102)*//*sid:46*/
      tmp = quicksort(left->struct_intlist__xM);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(103,103)*//*sid:47*/
      left->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(104,104)*//*sid:48*/
      left->struct_intlist__xM = tmp;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(105,105)*//*sid:49*/
      tmp = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(106,106)*//*sid:50*/
      tmp = quicksort(right->struct_intlist__xM);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(107,107)*//*sid:51*/
      right->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(108,108)*//*sid:52*/
      right->struct_intlist__xM = tmp;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(109,109)*//*sid:53*/
      tmp = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(110,110)*//*sid:54*/
      res = fold_concat3(left->struct_intlist__xM,pivot,
                         right->struct_intlist__xM);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(111,111)*//*sid:55*/
      { /*undefined sequence*/ 
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(111,111)*//*sid:56*/
        pivot = (struct intlist_ *)((struct char_P *)0);
        /*effects: pivot <- */
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(111,111)*//*sid:57*/
        tmp_3 = pivot;
        /*effects:  <- */
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(111,111)*//*sid:58*/
        right->struct_intlist__xM = tmp_3;
        /*effects: right->struct_intlist__xM <- tmp_3, right*/
        /*Loc=../../../cc/intlist-main-quick3-concat3.c:(111,111)*//*sid:59*/
        left->struct_intlist__xM = tmp_3;
        /*effects: left->struct_intlist__xM <- left*/
      }
    }
  }
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(114,114)*//*sid:60*/
  return (res);
}

/*Loc=../../../cc/intlist-main-quick3-concat3.c(120,120)*//*@ requires 
                                                                //id:2
                                                                (((((
                                                                    acyclic{
                                                                    Here}
                                                                    (x) ∧
                                                                    acyclic{
                                                                    Here}
                                                                    (y))
                                                                   ∧
                                                                   acyclic{
                                                                   Here}
                                                                   (h))
                                                                  ∧
                                                                  disjoint{
                                                                  Here}
                                                                  (x, y))
                                                                 ∧
                                                                 disjoint{
                                                                 Here}
                                                                 (y, h))
                                                                ∧
                                                                disjoint{
                                                                Here}
                                                                (x, h));
                                                              behavior default:
                                                                
                                                            
                                                          */
                                                          intlist fold_concat3(
intlist x , intlist y , intlist h ) 
{
  intlist r ;
  intlist z ;
  intlist zi ;
  intlist tmp_0 ;
  intlist li ;
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(122,122)*//*sid:61*/
  { /*undefined sequence*/ 
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(122,122)*//*sid:62*/
    li = (struct intlist_ *)((struct char_P *)0);
    /*effects: li <- */
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(122,122)*//*sid:63*/
    tmp_0 = li;
    /*effects: tmp_0 <- */
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(122,122)*//*sid:64*/
    zi = tmp_0;
    /*effects: zi <- */
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(122,122)*//*sid:65*/
    z = zi;
    /*effects: z <- */
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(122,122)*//*sid:66*/
    r = z;
    /*effects: r <- */
  }
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(124,124)*//*sid:67*/
  li = x;
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(125,125)*//*sid:68*/
  while (li != (struct char_P *)0) {
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(126,126)*//*sid:72*/
    zi = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(127,127)*//*sid:73*/
    zi->data = li->data;
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(128,128)*//*sid:74*/
    zi->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(129,129)*//*sid:76*/
    if (r == (struct char_P *)0) {
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(130,130)*//*sid:77*/
      r = zi;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(131,131)*//*sid:78*/
      z = zi;
    }
    else {
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(133,133)*//*sid:79*/
      z->next = zi;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(134,134)*//*sid:80*/
      z = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(135,135)*//*sid:81*/
      z = zi;
    }
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(137,137)*//*sid:82*/
    zi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(138,138)*//*sid:83*/
    zi = li->next;
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(139,139)*//*sid:84*/
    li = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(140,140)*//*sid:85*/
    li = zi;
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(141,141)*//*sid:86*/
    zi = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(145,145)*//*sid:87*/
  li = y;
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(146,146)*//*sid:88*/
  while (li != (struct char_P *)0) {
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(147,147)*//*sid:92*/
    zi = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(148,148)*//*sid:93*/
    zi->data = li->data;
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(149,149)*//*sid:94*/
    zi->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(150,150)*//*sid:96*/
    if (r == (struct char_P *)0) {
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(151,151)*//*sid:97*/
      r = zi;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(152,152)*//*sid:98*/
      z = zi;
    }
    else {
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(154,154)*//*sid:99*/
      z->next = zi;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(155,155)*//*sid:100*/
      z = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(156,156)*//*sid:101*/
      z = zi;
    }
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(158,158)*//*sid:102*/
    zi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(159,159)*//*sid:103*/
    zi = li->next;
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(160,160)*//*sid:104*/
    li = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(161,161)*//*sid:105*/
    li = zi;
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(162,162)*//*sid:106*/
    zi = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(166,166)*//*sid:107*/
  li = h;
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(167,167)*//*sid:108*/
  while (li != (struct char_P *)0) {
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(168,168)*//*sid:112*/
    zi = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(169,169)*//*sid:113*/
    zi->data = li->data;
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(170,170)*//*sid:114*/
    zi->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(171,171)*//*sid:116*/
    if (r == (struct char_P *)0) {
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(172,172)*//*sid:117*/
      r = zi;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(173,173)*//*sid:118*/
      z = zi;
    }
    else {
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(175,175)*//*sid:119*/
      z->next = zi;
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(176,176)*//*sid:120*/
      z = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../cc/intlist-main-quick3-concat3.c:(177,177)*//*sid:121*/
      z = zi;
    }
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(179,179)*//*sid:122*/
    zi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(180,180)*//*sid:123*/
    zi = li->next;
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(181,181)*//*sid:124*/
    li = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(182,182)*//*sid:125*/
    li = zi;
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(183,183)*//*sid:126*/
    zi = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(186,186)*//*sid:127*/
  z = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(187,187)*//*sid:128*/
  return (r);
}

/*Loc=../../../cc/intlist-main-quick3-concat3.c(193,193)*//*@ requires 
                                                                //id:3
                                                                (len ≡ 1);
                                                              behavior default:
                                                                
                                                            
                                                          */
                                                          void amain(
int len ) 
{
  intlist curr ;
  intlist head ;
  int i ;
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(199,199)*//*sid:129*/
  head = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(200,200)*//*sid:130*/
  curr = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(202,202)*//*sid:131*/
  i = 1;
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(202,202)*//*sid:132*/
  while (i <= len) {
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(203,203)*//*sid:136*/
    curr = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(204,204)*//*sid:137*/
    curr = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(205,205)*//*sid:138*/
    curr->data = len - i;
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(206,206)*//*sid:139*/
    curr->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(207,207)*//*sid:140*/
    curr->next = head;
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(208,208)*//*sid:141*/
    head = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(209,209)*//*sid:142*/
    head = curr;
    /*Loc=../../../cc/intlist-main-quick3-concat3.c:(202,202)*//*sid:143*/
    i ++;
  }
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(211,211)*//*sid:144*/
  curr = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(213,213)*//*sid:145*/
  curr = quicksort(head);
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(215,215)*//*sid:146*/
  head = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../cc/intlist-main-quick3-concat3.c:(217,217)*//*sid:148*/
  return;
}


