
all:
	$(VALGRIND) ../../../../frama-c-plugin/frama-c-Celia.byte -celia -celia-cinv-opt ucons.prop  ../../../c/intlist-lib-initSeq.c ../../../c/intlist-fold-searchV.c ../../../c/intlist-main-search.c

clean:
	rm *.shp pan* *.txt sid_*
