/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
struct char_P *malloc(unsigned int size ) ;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@ behavior default:
      assigns \nothing;  */
extern  __attribute__((__nothrow__)) void free(struct char_P *__ptr ) ;
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
intlist del_tail(intlist head ) ;
/*Loc=../../../c/intlist-lib-del_tail.c(9,9)*//*@ requires //id:67
                                                           acyclic{Here}
                                                           (head);
                                                  behavior default:
                                                    
                                                
                                              */
                                              intlist del_tail(intlist head ) 
{
  intlist h ;
  intlist hp ;
  intlist tmp ;
  intlist __retres ;
  /*Loc=../../../c/intlist-lib-del_tail.c:(11,11)*//*sid:1*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-lib-del_tail.c:(11,11)*//*sid:2*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*effects: tmp <- */
    /*Loc=../../../c/intlist-lib-del_tail.c:(11,11)*//*sid:3*/
    hp = tmp;
    /*effects: hp <- */
    /*Loc=../../../c/intlist-lib-del_tail.c:(11,11)*//*sid:4*/
    h = hp;
    /*effects: h <- */
  }
  /*Loc=../../../c/intlist-lib-del_tail.c:(12,12)*//*sid:6*/
  if (head == (struct char_P *)0) {
    /*Loc=../../../c/intlist-lib-del_tail.c:(13,13)*//*sid:7*/
    __retres = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-lib-del_tail.c:(13,13)*//*sid:30*/
    goto return_label;
  }
  /*Loc=../../../c/intlist-lib-del_tail.c:(14,14)*//*sid:9*/
  h = head;
  /*Loc=../../../c/intlist-lib-del_tail.c:(15,15)*//*sid:10*/
  tmp = h->next;
  /*Loc=../../../c/intlist-lib-del_tail.c:(16,16)*//*sid:12*/
  if (tmp == (struct char_P *)0) {
    /*Loc=../../../c/intlist-lib-del_tail.c:(17,17)*//*sid:13*/
    free((struct char_P *)head);
    /*Loc=../../../c/intlist-lib-del_tail.c:(18,18)*//*sid:14*/
    __retres = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-lib-del_tail.c:(18,18)*//*sid:31*/
    goto return_label;
  }
  /*Loc=../../../c/intlist-lib-del_tail.c:(20,20)*//*sid:16*/
  while (tmp != (struct char_P *)0) {
    /*Loc=../../../c/intlist-lib-del_tail.c:(21,21)*//*sid:20*/
    hp = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-lib-del_tail.c:(22,22)*//*sid:21*/
    hp = h;
    /*Loc=../../../c/intlist-lib-del_tail.c:(23,23)*//*sid:22*/
    h = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-lib-del_tail.c:(24,24)*//*sid:23*/
    h = tmp;
    /*Loc=../../../c/intlist-lib-del_tail.c:(25,25)*//*sid:24*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-lib-del_tail.c:(26,26)*//*sid:25*/
    tmp = h->next;
  }
  /*Loc=../../../c/intlist-lib-del_tail.c:(28,28)*//*sid:26*/
  free((struct char_P *)h);
  /*Loc=../../../c/intlist-lib-del_tail.c:(29,29)*//*sid:27*/
  hp->next = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-lib-del_tail.c:(30,30)*//*sid:28*/
  hp = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-lib-del_tail.c:(31,31)*//*sid:29*/
  __retres = head;
  /*Loc=../../../c/intlist-lib-del_tail.c:(31,31)*/return_label: /* internal */ 
  /*sid:32*/
  return (__retres);
}


