/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
typedef unsigned int size_t;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@ behavior default:
      assigns \at(\result,Post) \from __size;  */
extern  __attribute__((__nothrow__)) struct char_P *malloc(size_t __size )  __attribute__((
__malloc__)) ;
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
intlist fold_clone(intlist x ) ;
intlist fold2_rec_concat(intlist x_0 , intlist y ) ;
/*Loc=../../../c/intlist-fold2-concat_rec.c(9,9)*//*@ requires //id:134
                                                               ((acyclic{
                                                                 Here}
                                                                 (x_0)
                                                                ∧
                                                                acyclic{
                                                                Here}
                                                                (y))
                                                               ∧
                                                               disjoint{
                                                               Here}(x_0, y));
                                                      behavior default:
                                                        
                                                    
                                                  */
                                                  intlist fold2_rec_concat(
intlist x_0 , intlist y ) 
{
  intlist r ;
  intlist tmp ;
  intlist rr ;
  /*Loc=../../../c/intlist-fold2-concat_rec.c:(11,11)*//*sid:1*/
  r = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-fold2-concat_rec.c:(12,12)*//*sid:3*/
  if (x_0 == (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold2-concat_rec.c:(13,13)*//*sid:4*/
    r = fold_clone(y);
  }
  else {
    /*Loc=../../../c/intlist-fold2-concat_rec.c:(16,16)*//*sid:5*/
    { /*undefined sequence*/ 
      /*Loc=../../../c/intlist-fold2-concat_rec.c:(16,16)*//*sid:6*/
      rr = (struct intlist_ *)((struct char_P *)0);
      /*effects: rr <- */
      /*Loc=../../../c/intlist-fold2-concat_rec.c:(16,16)*//*sid:7*/
      tmp = rr;
      /*effects: tmp <- */
    }
    /*Loc=../../../c/intlist-fold2-concat_rec.c:(17,17)*//*sid:8*/
    tmp = x_0->next;
    /*Loc=../../../c/intlist-fold2-concat_rec.c:(18,18)*//*sid:9*/
    r = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-fold2-concat_rec.c:(19,19)*//*sid:10*/
    r->data = x_0->data;
    /*Loc=../../../c/intlist-fold2-concat_rec.c:(20,20)*//*sid:11*/
    r->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold2-concat_rec.c:(21,21)*//*sid:12*/
    rr = fold2_rec_concat(tmp,y);
    /*Loc=../../../c/intlist-fold2-concat_rec.c:(22,22)*//*sid:13*/
    r->next = rr;
    /*Loc=../../../c/intlist-fold2-concat_rec.c:(23,23)*//*sid:14*/
    { /*undefined sequence*/ 
      /*Loc=../../../c/intlist-fold2-concat_rec.c:(23,23)*//*sid:15*/
      rr = (struct intlist_ *)((struct char_P *)0);
      /*effects: rr <- */
      /*Loc=../../../c/intlist-fold2-concat_rec.c:(23,23)*//*sid:16*/
      tmp = rr;
      /*effects: tmp <- */
    }
  }
  /*Loc=../../../c/intlist-fold2-concat_rec.c:(25,25)*//*sid:17*/
  return (r);
}

/*Loc=../../../c/intlist-fold-clone.c(9,9)*//*@ requires //id:67
                                                         acyclic{Here}(x);
                                                behavior default:
                                                  
                                              
                                            */
                                            intlist fold_clone(intlist x ) 
{
  intlist xi ;
  intlist y_0 ;
  intlist yi ;
  intlist z ;
  /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:18*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:19*/
    z = (struct intlist_ *)((struct char_P *)0);
    /*effects: z <- */
    /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:20*/
    yi = z;
    /*effects: yi <- */
    /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:21*/
    y_0 = yi;
    /*effects: y_0 <- */
    /*Loc=../../../c/intlist-fold-clone.c:(11,11)*//*sid:22*/
    xi = y_0;
    /*effects: xi <- */
  }
  /*Loc=../../../c/intlist-fold-clone.c:(12,12)*//*sid:23*/
  xi = x;
  /*Loc=../../../c/intlist-fold-clone.c:(13,13)*//*sid:24*/
  while (xi != (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold-clone.c:(14,14)*//*sid:28*/
    z = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-fold-clone.c:(15,15)*//*sid:29*/
    z->data = xi->data;
    /*Loc=../../../c/intlist-fold-clone.c:(16,16)*//*sid:30*/
    z->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-clone.c:(17,17)*//*sid:32*/
    if (y_0 == (struct char_P *)0) {
      /*Loc=../../../c/intlist-fold-clone.c:(18,18)*//*sid:33*/
      y_0 = z;
    }
    else {
      /*Loc=../../../c/intlist-fold-clone.c:(20,20)*//*sid:34*/
      yi->next = z;
    }
    /*Loc=../../../c/intlist-fold-clone.c:(21,21)*//*sid:35*/
    yi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-clone.c:(22,22)*//*sid:36*/
    yi = z;
    /*Loc=../../../c/intlist-fold-clone.c:(23,23)*//*sid:37*/
    z = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-clone.c:(24,24)*//*sid:38*/
    z = xi->next;
    /*Loc=../../../c/intlist-fold-clone.c:(25,25)*//*sid:39*/
    xi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-clone.c:(26,26)*//*sid:40*/
    xi = z;
    /*Loc=../../../c/intlist-fold-clone.c:(27,27)*//*sid:41*/
    z = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-fold-clone.c:(29,29)*//*sid:42*/
  yi = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-fold-clone.c:(30,30)*//*sid:43*/
  return (y_0);
}


