/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
/*@ behavior default:
      assigns \nothing;  */
struct char_P *malloc(unsigned int size ) ;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
/*Loc=../../../c/intlist-sort-bubble.c(6,6)*//*@ requires //id:67
                                                          acyclic{Here}(x);
                                                 behavior default:
                                                   
                                               
                                             */
                                             void bubblesort(intlist x ) 
{
  intlist xi ;
  intlist xin ;
  int v ;
  int k ;
  /*Loc=../../../c/intlist-sort-bubble.c:(9,9)*//*sid:1*/
  k = 1;
  /*Loc=../../../c/intlist-sort-bubble.c:(10,10)*//*sid:2*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-sort-bubble.c:(10,10)*//*sid:3*/
    xin = (struct intlist_ *)((struct char_P *)0);
    /*effects: xin <- */
    /*Loc=../../../c/intlist-sort-bubble.c:(10,10)*//*sid:4*/
    xi = xin;
    /*effects: xi <- */
  }
  /*Loc=../../../c/intlist-sort-bubble.c:(11,11)*//*sid:5*/
  while (k == 1) {
    /*Loc=../../../c/intlist-sort-bubble.c:(12,12)*//*sid:9*/
    k = 0;
    /*Loc=../../../c/intlist-sort-bubble.c:(13,13)*//*sid:10*/
    xi = x;
    /*Loc=../../../c/intlist-sort-bubble.c:(14,14)*//*sid:11*/
    xin = x->next;
    /*Loc=../../../c/intlist-sort-bubble.c:(15,15)*//*sid:12*/
    while (xi != (struct char_P *)0) {
      /*Loc=../../../c/intlist-sort-bubble.c:(16,16)*//*sid:17*/
      if (xin == (struct char_P *)0) {
        /*Loc=../../../c/intlist-sort-bubble.c:(17,17)*//*sid:18*/
        break;
      }
      /*Loc=../../../c/intlist-sort-bubble.c:(18,18)*//*sid:21*/
      if (xi->data > xin->data) {
        /*Loc=../../../c/intlist-sort-bubble.c:(19,19)*//*sid:22*/
        v = xi->data;
        /*Loc=../../../c/intlist-sort-bubble.c:(20,20)*//*sid:23*/
        xi->data = xin->data;
        /*Loc=../../../c/intlist-sort-bubble.c:(21,21)*//*sid:24*/
        xin->data = v;
        /*Loc=../../../c/intlist-sort-bubble.c:(22,22)*//*sid:25*/
        k = 1;
      }
      /*Loc=../../../c/intlist-sort-bubble.c:(24,24)*//*sid:27*/
      xi = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-sort-bubble.c:(25,25)*//*sid:28*/
      xi = xin;
      /*Loc=../../../c/intlist-sort-bubble.c:(26,26)*//*sid:29*/
      xin = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-sort-bubble.c:(27,27)*//*sid:30*/
      xin = xi->next;
    }
    /*Loc=../../../c/intlist-sort-bubble.c:(29,29)*//*sid:31*/
    { /*undefined sequence*/ 
      /*Loc=../../../c/intlist-sort-bubble.c:(29,29)*//*sid:32*/
      xin = (struct intlist_ *)((struct char_P *)0);
      /*effects: xin <- */
      /*Loc=../../../c/intlist-sort-bubble.c:(29,29)*//*sid:33*/
      xi = xin;
      /*effects: xi <- */
    }
  }
  /*Loc=../../../c/intlist-sort-bubble.c:(31,31)*//*sid:35*/
  return;
}


