/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
/*@ behavior default:
      assigns \nothing;  */
struct char_P *malloc(unsigned int size ) ;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
void map_initSeqEven(intlist head , int v ) ;
/*Loc=../../../c/intlist-map-initSeqEven.c(9,9)*//*@ requires //id:67
                                                              acyclic{
                                                              Here}(head);
                                                     behavior default:
                                                       
                                                   
                                                 */
                                                 void map_initSeqEven(
intlist head , int v ) 
{
  intlist h ;
  intlist tmp ;
  /*Loc=../../../c/intlist-map-initSeqEven.c:(11,11)*//*sid:1*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-map-initSeqEven.c:(11,11)*//*sid:2*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*effects: tmp <- */
    /*Loc=../../../c/intlist-map-initSeqEven.c:(11,11)*//*sid:3*/
    h = tmp;
    /*effects: h <- */
  }
  /*Loc=../../../c/intlist-map-initSeqEven.c:(12,12)*//*sid:4*/
  h = head;
  /*Loc=../../../c/intlist-map-initSeqEven.c:(13,13)*//*sid:5*/
  while (h != (struct char_P *)0) {
    /*Loc=../../../c/intlist-map-initSeqEven.c:(14,14)*//*sid:9*/
    h->data = v;
    /*Loc=../../../c/intlist-map-initSeqEven.c:(15,15)*//*sid:10*/
    v += 2;
    /*Loc=../../../c/intlist-map-initSeqEven.c:(16,16)*//*sid:11*/
    tmp = h->next;
    /*Loc=../../../c/intlist-map-initSeqEven.c:(17,17)*//*sid:12*/
    h = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-map-initSeqEven.c:(18,18)*//*sid:13*/
    h = tmp;
    /*Loc=../../../c/intlist-map-initSeqEven.c:(19,19)*//*sid:14*/
    tmp = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-map-initSeqEven.c:(21,21)*//*sid:16*/
  return;
}


