/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
/*@ behavior default:
      assigns \nothing;  */
struct char_P *malloc(unsigned int size ) ;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
/*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c(10,10)*/
/*@ requires //id:67
             acyclic{Here}(x);
    behavior default:
       
*/
intlist fold_reverse(intlist x ) 
{
  intlist r ;
  intlist xi ;
  intlist tmp ;
  /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(12,12)*//*sid:1*/
  { /*undefined sequence*/ 
    /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(12,12)*//*sid:2*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*effects: tmp <- */
    /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(12,12)*//*sid:3*/
    xi = tmp;
    /*effects: xi <- */
    /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(12,12)*//*sid:4*/
    r = xi;
    /*effects: r <- */
  }
  /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(13,13)*//*sid:5*/
  xi = x;
  /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(14,14)*//*sid:6*/
  while (xi != (struct char_P *)0) {
    /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(15,15)*//*sid:10*/
    tmp = xi->next;
    /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(16,16)*//*sid:11*/
    xi->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(17,17)*//*sid:12*/
    xi->next = r;
    /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(18,18)*//*sid:13*/
    r = (struct intlist_ *)((struct char_P *)0);
    /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(19,19)*//*sid:14*/
    r = xi;
    /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(20,20)*//*sid:15*/
    xi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(21,21)*//*sid:16*/
    xi = tmp;
    /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(22,22)*//*sid:17*/
    tmp = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=/home/verif/sighirea/Parallelisme/tools/cinv/samples/c/intlist-fold-reverse.c:(24,24)*//*sid:18*/
  return (r);
}


