/* Generated by Frama-C */
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
/*@ behavior default:
      assigns \nothing;  */
struct char_P *malloc(unsigned int size ) ;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
void map2_addV_eq(intlist x , intlist y , int v ) ;
/*Loc=../../../c/intlist-map2-addV_eq.c(11,11)*//*@ requires //id:67
                                                             (acyclic{
                                                              Here}(x)
                                                             ∧
                                                             acyclic{Here}(y));
                                                    requires //id:68
                                                             (len(x) ≡
                                                             len(y));
                                                    requires //id:23
                                                             ((acyclic{
                                                               Here}(x)
                                                              ∧
                                                              acyclic{
                                                              Here}(y))
                                                             ∧
                                                             disjoint{
                                                             Here}(x, y));
                                                    requires //id:24
                                                             (len(x) ≡
                                                             len(y));
                                                    behavior default:
                                                      
                                                  
                                                */
                                                void map2_addV_eq(intlist x ,
                                                                  intlist y ,
                                                                  int v ) 
{
  intlist xi ;
  intlist yi ;
  intlist tmp ;
  /*Loc=../../../c/intlist-map2-addV_eq.c:(13,13)*//*sid:1*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-map2-addV_eq.c:(13,13)*//*sid:2*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*effects: tmp <- */
    /*Loc=../../../c/intlist-map2-addV_eq.c:(13,13)*//*sid:3*/
    yi = tmp;
    /*effects: yi <- */
    /*Loc=../../../c/intlist-map2-addV_eq.c:(13,13)*//*sid:4*/
    xi = yi;
    /*effects: xi <- */
  }
  /*Loc=../../../c/intlist-map2-addV_eq.c:(14,14)*//*sid:5*/
  xi = x;
  /*Loc=../../../c/intlist-map2-addV_eq.c:(15,15)*//*sid:6*/
  yi = y;
  /*Loc=../../../c/intlist-map2-addV_eq.c:(16,16)*//*sid:7*/
  while (xi != (struct char_P *)0) {
    /*Loc=../../../c/intlist-map2-addV_eq.c:(17,17)*//*sid:11*/
    yi->data = xi->data + v;
    /*Loc=../../../c/intlist-map2-addV_eq.c:(18,18)*//*sid:12*/
    tmp = xi->next;
    /*Loc=../../../c/intlist-map2-addV_eq.c:(19,19)*//*sid:13*/
    xi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-map2-addV_eq.c:(20,20)*//*sid:14*/
    xi = tmp;
    /*Loc=../../../c/intlist-map2-addV_eq.c:(21,21)*//*sid:15*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-map2-addV_eq.c:(22,22)*//*sid:16*/
    tmp = yi->next;
    /*Loc=../../../c/intlist-map2-addV_eq.c:(23,23)*//*sid:17*/
    yi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-map2-addV_eq.c:(24,24)*//*sid:18*/
    yi = tmp;
    /*Loc=../../../c/intlist-map2-addV_eq.c:(25,25)*//*sid:19*/
    tmp = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-map2-addV_eq.c:(27,27)*//*sid:21*/
  return;
}


