
all:
	$(CINV)/bin/frama-c-Celia.byte -celia -celia-cinv-opt mset.prop $(CINV)/samples/c/intlist-lib-init.c $(CINV)/samples/c/intlist-fold-clone.c $(CINV)/samples/c/intlist-fold-splitV.c $(CINV)/samples/c/intlist-fold2-concat.c $(CINV)/samples/c/intlist-sort-quick1.c

clean:
	rm *.shp pan* *.txt
