/* Generated by Frama-C */
struct struct_intlist__xP {
   struct intlist_ *struct_intlist__xM ;
};
struct char_P {
   char char_M ;
};
struct void_P {
   
};
/*@ behavior default:
      assigns \nothing;  */
void free(struct char_P *ptr ) ;
typedef unsigned int size_t;
struct intlist_;
typedef struct intlist_ *intlist;
struct intlist_ {
   int data ;
   intlist next ;
};
/*@ behavior default:
      assigns \at(\result,Post) \from __size;  */
extern  __attribute__((__nothrow__)) struct char_P *malloc(size_t __size )  __attribute__((
__malloc__)) ;
/*@
predicate reach{L}(intlist from, intlist to) =
  ((from ≡ to) ∨ (\valid(from) ∧ reach(from->next, to)));
 */
/*@ predicate acyclic{L}(intlist l) = reach{L}(l, \null);
 */
/*@
predicate disjoint{L}(intlist l1, intlist l2) =
  ¬((∃ struct intlist_ *l_0; (reach{L}(l1, l_0) ∧ reach{L}(l2, l_0))));
 */
/*@
predicate disjoint3{L}(intlist l1_0, intlist l2_0, intlist l3) =
  ((disjoint{L}(l1_0, l2_0) ∧ disjoint{L}(l2_0, l3)) ∧
  disjoint{L}(l1_0, l3));
 */
/*@ logic ℤ len(intlist ptr) = ptr≡\null? 0: 1+len(ptr->next);
 */
void fold_split(intlist x , int v , struct struct_intlist__xP *l ,
                struct struct_intlist__xP *u ) ;
/*Loc=../../../c/intlist-fold-splitV.c(9,9)*//*@ requires //id:67
                                                          acyclic{Here}(x);
                                                 behavior default:
                                                   
                                               
                                             */
                                             void fold_split(intlist x ,
                                                             int v ,
                                                             struct struct_intlist__xP *l ,
                                                             struct struct_intlist__xP *u ) 
{
  intlist xi ;
  intlist y ;
  intlist tmp ;
  /*Loc=../../../c/intlist-fold-splitV.c:(11,11)*//*sid:1*/
  { /*undefined sequence*/ 
    /*Loc=../../../c/intlist-fold-splitV.c:(11,11)*//*sid:2*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*effects: tmp <- */
    /*Loc=../../../c/intlist-fold-splitV.c:(11,11)*//*sid:3*/
    y = tmp;
    /*effects: y <- */
    /*Loc=../../../c/intlist-fold-splitV.c:(11,11)*//*sid:4*/
    xi = y;
    /*effects: xi <- */
  }
  /*Loc=../../../c/intlist-fold-splitV.c:(12,12)*//*sid:5*/
  xi = x;
  /*Loc=../../../c/intlist-fold-splitV.c:(13,13)*//*sid:6*/
  l->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-fold-splitV.c:(14,14)*//*sid:7*/
  u->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
  /*Loc=../../../c/intlist-fold-splitV.c:(15,15)*//*sid:8*/
  while (xi != (struct char_P *)0) {
    /*Loc=../../../c/intlist-fold-splitV.c:(16,16)*//*sid:12*/
    y = (intlist )malloc(sizeof(struct intlist_ ));
    /*Loc=../../../c/intlist-fold-splitV.c:(17,17)*//*sid:13*/
    y->data = xi->data;
    /*Loc=../../../c/intlist-fold-splitV.c:(18,18)*//*sid:14*/
    y->next = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-splitV.c:(19,19)*//*sid:15*/
    tmp = xi->next;
    /*Loc=../../../c/intlist-fold-splitV.c:(20,20)*//*sid:16*/
    xi = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-splitV.c:(21,21)*//*sid:17*/
    xi = tmp;
    /*Loc=../../../c/intlist-fold-splitV.c:(22,22)*//*sid:18*/
    tmp = (struct intlist_ *)((struct char_P *)0);
    /*Loc=../../../c/intlist-fold-splitV.c:(23,23)*//*sid:20*/
    if (y->data <= v) {
      /*Loc=../../../c/intlist-fold-splitV.c:(24,24)*//*sid:21*/
      y->next = l->struct_intlist__xM;
      /*Loc=../../../c/intlist-fold-splitV.c:(25,25)*//*sid:22*/
      l->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold-splitV.c:(26,26)*//*sid:23*/
      l->struct_intlist__xM = y;
    }
    else {
      /*Loc=../../../c/intlist-fold-splitV.c:(28,28)*//*sid:24*/
      y->next = u->struct_intlist__xM;
      /*Loc=../../../c/intlist-fold-splitV.c:(29,29)*//*sid:25*/
      u->struct_intlist__xM = (struct intlist_ *)((struct char_P *)0);
      /*Loc=../../../c/intlist-fold-splitV.c:(30,30)*//*sid:26*/
      u->struct_intlist__xM = y;
    }
    /*Loc=../../../c/intlist-fold-splitV.c:(32,32)*//*sid:27*/
    y = (struct intlist_ *)((struct char_P *)0);
  }
  /*Loc=../../../c/intlist-fold-splitV.c:(34,34)*//*sid:29*/
  return;
}


