
all:
	$(CINV)/bin/frama-c-Celia.byte -celia -celia-cinv-opt ucons.prop $(CINV)/samples/c/intlist-fold-clone.c $(CINV)/samples/c/intlist-fold-splitV.c $(CINV)/samples/c/intlist-fold2-concat.c $(CINV)/samples/c/intlist-sort-quick2.c

clean:
	rm *.shp pan* *.txt
